//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounting_output
    {
        public int accounting_output_id { get; set; }
        public int transaction_id { get; set; }
        public int status_id { get; set; }
        public System.DateTime amount_start_date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> amount_ccy_id { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> capital { get; set; }
        public Nullable<decimal> interest { get; set; }
        public string payment_method { get; set; }
        public string beneficiary { get; set; }
        public string payment_reference { get; set; }
        public Nullable<System.DateTime> value_date { get; set; }
        public Nullable<int> counterparty_id1 { get; set; }
        public Nullable<int> counterparty_id2 { get; set; }
        public Nullable<int> counterparty_id3 { get; set; }
        public Nullable<decimal> outstanding_amount { get; set; }
        public Nullable<decimal> fees_amount { get; set; }
        public Nullable<bool> inserted_automatically { get; set; }
        public string event_type { get; set; }
        public Nullable<System.DateTime> event_date { get; set; }
        public string amount_type { get; set; }
        public Nullable<decimal> amount_output { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual counterparty counterparty1 { get; set; }
        public virtual counterparty counterparty2 { get; set; }
        public virtual currency currency { get; set; }
        public virtual status status { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
