//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class additional_data
    {
        public additional_data()
        {
            this.additional_data_profiles = new HashSet<additional_data_profiles>();
            this.additional_data_domain = new HashSet<additional_data_domain>();
            this.counterparty_add_data = new HashSet<counterparty_add_data>();
            this.counterparty_add_data_litigation = new HashSet<counterparty_add_data_litigation>();
            this.credit_file_add_data = new HashSet<credit_file_add_data>();
            this.mitigant_add_data = new HashSet<mitigant_add_data>();
            this.transaction_add_data = new HashSet<transaction_add_data>();
        }
    
        public int data_id { get; set; }
        public string screen { get; set; }
        public string data_shortname { get; set; }
        public string data_name { get; set; }
        public string data_type { get; set; }
        public Nullable<int> data_length { get; set; }
        public Nullable<bool> mandatory_flag { get; set; }
        public string condition { get; set; }
        public Nullable<bool> list_flag { get; set; }
        public Nullable<bool> enable_flag { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<bool> quick_input { get; set; }
        public Nullable<bool> advanced_mode { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<additional_data_profiles> additional_data_profiles { get; set; }
        public virtual ICollection<additional_data_domain> additional_data_domain { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<counterparty_add_data> counterparty_add_data { get; set; }
        public virtual ICollection<counterparty_add_data_litigation> counterparty_add_data_litigation { get; set; }
        public virtual ICollection<credit_file_add_data> credit_file_add_data { get; set; }
        public virtual ICollection<mitigant_add_data> mitigant_add_data { get; set; }
        public virtual ICollection<transaction_add_data> transaction_add_data { get; set; }
    }
}
