//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class aggregation_criteria
    {
        public int aggregation_criteria_id { get; set; }
        public string aggregation_criteria_shortname { get; set; }
        public string aggregation_criteria_name { get; set; }
        public string aggregation_criteria_description { get; set; }
        public string criteria_table { get; set; }
        public string criteria_column { get; set; }
        public Nullable<bool> filter_on { get; set; }
        public string filter_table { get; set; }
        public string filter_column { get; set; }
        public string filter_operator { get; set; }
        public string filter_value { get; set; }
        public Nullable<bool> with_limit_only { get; set; }
        public string relation_table { get; set; }
        public string child_column { get; set; }
        public string parent_column { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
    }
}
