//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class bkt_discriminatory_history_detail
    {
        public int bkt_discriminatory_history_detail_id { get; set; }
        public System.DateTime bkt_date { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int rating_id { get; set; }
        public Nullable<int> population_count { get; set; }
        public Nullable<int> default_cases { get; set; }
        public Nullable<int> good_cases { get; set; }
        public Nullable<decimal> default_rate { get; set; }
        public Nullable<decimal> cumul_goods { get; set; }
        public Nullable<decimal> cumul_bads { get; set; }
        public Nullable<decimal> cumul_population { get; set; }
        public Nullable<decimal> variation_cumul_bads { get; set; }
        public Nullable<decimal> sum_cumul_population { get; set; }
        public Nullable<decimal> field_g { get; set; }
        public Nullable<decimal> field_id { get; set; }
        public Nullable<decimal> gini { get; set; }
        public Nullable<decimal> idd { get; set; }
        public Nullable<decimal> gmp_model { get; set; }
        public Nullable<decimal> gmp_naive { get; set; }
        public Nullable<decimal> gap { get; set; }
        public int counterparty_id { get; set; }
        public string counterparty_final_state { get; set; }
        public Nullable<System.DateTime> default_date { get; set; }
        public Nullable<int> counterparty_final_rating_id { get; set; }
        public Nullable<decimal> counterparty_pd { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual rating rating { get; set; }
        public virtual rating rating1 { get; set; }
    }
}
