//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class bkt_ccf_history
    {
        public int bkt_ccf_history_id { get; set; }
        public System.DateTime bkt_date { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public decimal tolerance_rate { get; set; }
        public int transaction_type_id { get; set; }
        public Nullable<decimal> ead { get; set; }
        public Nullable<decimal> erad { get; set; }
        public string traffic { get; set; }
        public Nullable<decimal> bccf { get; set; }
        public Nullable<decimal> ccf { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual transaction_type transaction_type { get; set; }
    }
}
