//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class collect_question
    {
        public string item { get; set; }
        public int item_id { get; set; }
        public string collect_question1 { get; set; }
        public string answer { get; set; }
        public Nullable<int> executed_by { get; set; }
        public Nullable<System.DateTime> execution_date { get; set; }
        public string step_name { get; set; }
        public int sequence_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string wf_name { get; set; }
    
        public virtual software_user software_user { get; set; }
    }
}
