//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class communication_log
    {
        public int communication_log_id { get; set; }
        public Nullable<int> from_user_id { get; set; }
        public Nullable<int> to_user_id { get; set; }
        public string to_multiple_users { get; set; }
        public Nullable<int> to_group_id { get; set; }
        public string to_multiple_groups { get; set; }
        public Nullable<int> to_profile_id { get; set; }
        public string to_multiple_profiles { get; set; }
        public string message_content { get; set; }
        public string message_priority { get; set; }
        public string item { get; set; }
        public Nullable<int> item_id { get; set; }
        public string item_link { get; set; }
        public Nullable<System.DateTime> sending_timestamp { get; set; }
        public Nullable<System.DateTime> reading_timestamp { get; set; }
        public byte[] attached_document { get; set; }
        public Nullable<bool> read_notification { get; set; }
        public Nullable<int> receiver_status { get; set; }
        public Nullable<int> message_status { get; set; }
    }
}
