//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class constant_matrix
    {
        public int constant_matrix_id { get; set; }
        public string constant_matrix_shortname { get; set; }
        public string criteria1_text { get; set; }
        public Nullable<decimal> criteria1_decimal { get; set; }
        public Nullable<int> criteria1_ccy { get; set; }
        public string criteria1_table { get; set; }
        public string criteria1_column { get; set; }
        public string criteria2_text { get; set; }
        public Nullable<decimal> criteria2_decimal { get; set; }
        public Nullable<int> criteria2_ccy { get; set; }
        public string criteria2_table { get; set; }
        public string criteria2_column { get; set; }
        public string criteria3_text { get; set; }
        public Nullable<decimal> criteria3_decimal { get; set; }
        public Nullable<int> criteria3_ccy { get; set; }
        public string criteria3_table { get; set; }
        public string criteria3_column { get; set; }
        public string criteria4_text { get; set; }
        public Nullable<decimal> criteria4_decimal { get; set; }
        public Nullable<int> criteria4_ccy { get; set; }
        public string criteria4_table { get; set; }
        public string criteria4_column { get; set; }
        public string criteria5_text { get; set; }
        public Nullable<decimal> criteria5_decimal { get; set; }
        public Nullable<int> criteria5_ccy { get; set; }
        public string criteria5_table { get; set; }
        public string criteria5_column { get; set; }
        public string criteria6_text { get; set; }
        public Nullable<decimal> criteria6_decimal { get; set; }
        public Nullable<int> criteria6_ccy { get; set; }
        public string criteria6_table { get; set; }
        public string criteria6_column { get; set; }
        public string criteria7_text { get; set; }
        public Nullable<decimal> criteria7_decimal { get; set; }
        public Nullable<int> criteria7_ccy { get; set; }
        public string criteria7_table { get; set; }
        public string criteria7_column { get; set; }
        public string criteria8_text { get; set; }
        public Nullable<decimal> criteria8_decimal { get; set; }
        public Nullable<int> criteria8_ccy { get; set; }
        public string criteria8_table { get; set; }
        public string criteria8_column { get; set; }
        public string criteria9_text { get; set; }
        public Nullable<decimal> criteria9_decimal { get; set; }
        public Nullable<int> criteria9_ccy { get; set; }
        public string criteria9_table { get; set; }
        public string criteria9_column { get; set; }
        public string criteria10_text { get; set; }
        public Nullable<decimal> criteria10_decimal { get; set; }
        public Nullable<int> criteria10_ccy { get; set; }
        public string criteria10_table { get; set; }
        public string criteria10_column { get; set; }
        public string value1_text { get; set; }
        public Nullable<decimal> value1_decimal { get; set; }
        public Nullable<int> value1_ccy { get; set; }
        public string value2_text { get; set; }
        public Nullable<decimal> value2_decimal { get; set; }
        public Nullable<int> value2_ccy { get; set; }
        public string value3_text { get; set; }
        public Nullable<decimal> value3_decimal { get; set; }
        public Nullable<int> value3_ccy { get; set; }
        public string value4_text { get; set; }
        public Nullable<decimal> value4_decimal { get; set; }
        public Nullable<int> value4_ccy { get; set; }
        public string value5_text { get; set; }
        public Nullable<decimal> value5_decimal { get; set; }
        public Nullable<int> value5_ccy { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string value6_text { get; set; }
        public Nullable<decimal> value6_decimal { get; set; }
        public Nullable<int> value6_ccy { get; set; }
        public string value7_text { get; set; }
        public Nullable<decimal> value7_decimal { get; set; }
        public Nullable<int> value7_ccy { get; set; }
        public string value8_text { get; set; }
        public Nullable<decimal> value8_decimal { get; set; }
        public Nullable<int> value8_ccy { get; set; }
        public string value9_text { get; set; }
        public Nullable<decimal> value9_decimal { get; set; }
        public Nullable<int> value9_ccy { get; set; }
        public string value10_text { get; set; }
        public Nullable<decimal> value10_decimal { get; set; }
        public Nullable<int> value10_ccy { get; set; }
    }
}
