//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_internal_rating_warning
    {
        public int counterparty_internal_rating_warning_id { get; set; }
        public Nullable<int> counterparty_internal_rating_id { get; set; }
        public Nullable<int> warning_signal_id { get; set; }
        public string comment { get; set; }
    
        public virtual counterparty_internal_rating counterparty_internal_rating { get; set; }
        public virtual warning_signal warning_signal { get; set; }
    }
}
