//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_classification
    {
        public counterparty_classification()
        {
            this.counterparty = new HashSet<counterparty>();
            this.counterparty1 = new HashSet<counterparty>();
        }
    
        public int counterparty_class_id { get; set; }
        public string counterparty_class_shortname { get; set; }
        public string counterparty_class_name { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<counterparty> counterparty { get; set; }
        public virtual ICollection<counterparty> counterparty1 { get; set; }
    }
}
