//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty
    {
        public counterparty()
        {
            this.accounting_output = new HashSet<accounting_output>();
            this.accounting_output1 = new HashSet<accounting_output>();
            this.accounting_output2 = new HashSet<accounting_output>();
            this.bkt_discriminatory_history_detail = new HashSet<bkt_discriminatory_history_detail>();
            this.bkt_lgd_history = new HashSet<bkt_lgd_history>();
            this.bkt_pd_history_detail = new HashSet<bkt_pd_history_detail>();
            this.core_banking = new HashSet<core_banking>();
            this.counterparty_account = new HashSet<counterparty_account>();
            this.counterparty_account1 = new HashSet<counterparty_account>();
            this.counterparty_action = new HashSet<counterparty_action>();
            this.counterparty_amount = new HashSet<counterparty_amount>();
            this.counterparty_contacts = new HashSet<counterparty_contacts>();
            this.counterparty1 = new HashSet<counterparty>();
            this.counterparty_cpty = new HashSet<counterparty_cpty>();
            this.counterparty_cpty1 = new HashSet<counterparty_cpty>();
            this.counterparty_credit_state_history = new HashSet<counterparty_credit_state_history>();
            this.counterparty_external_rating = new HashSet<counterparty_external_rating>();
            this.counterparty_financial_data = new HashSet<counterparty_financial_data>();
            this.counterparty_financial_structure = new HashSet<counterparty_financial_structure>();
            this.counterparty_generic = new HashSet<counterparty_generic>();
            this.counterparty_internal_rating = new HashSet<counterparty_internal_rating>();
            this.counterparty_parent = new HashSet<counterparty_parent>();
            this.counterparty_parent1 = new HashSet<counterparty_parent>();
            this.counterparty_qualitative_data = new HashSet<counterparty_qualitative_data>();
            this.counterparty_qualitative_element = new HashSet<counterparty_qualitative_element>();
            this.counterparty_qualitative_node = new HashSet<counterparty_qualitative_node>();
            this.counterparty_shareholders = new HashSet<counterparty_shareholders>();
            this.counterparty_user = new HashSet<counterparty_user>();
            this.counterparty_address = new HashSet<counterparty_address>();
            this.credit_file = new HashSet<credit_file>();
            this.credit_file_cpty = new HashSet<credit_file_cpty>();
            this.financial_analysis_session = new HashSet<financial_analysis_session>();
            this.marketing_action = new HashSet<marketing_action>();
            this.mitigant_participant = new HashSet<mitigant_participant>();
            this.outstanding = new HashSet<outstanding>();
            this.payment = new HashSet<payment>();
            this.recovery_type_parameter_counterparty = new HashSet<recovery_type_parameter_counterparty>();
            this.security = new HashSet<security>();
            this.transaction_amount = new HashSet<transaction_amount>();
            this.transaction_amount1 = new HashSet<transaction_amount>();
            this.transaction = new HashSet<transaction>();
            this.transaction_reallocation = new HashSet<transaction_reallocation>();
            this.transaction_recovery = new HashSet<transaction_recovery>();
            this.transaction_recovery1 = new HashSet<transaction_recovery>();
        }
    
        public int counterparty_id { get; set; }
        public string counterparty_shortname { get; set; }
        public string counterparty_name { get; set; }
        public string counterparty_name2 { get; set; }
        public Nullable<int> counterparty_type_id { get; set; }
        public Nullable<int> scoring_template_id { get; set; }
        public Nullable<int> counterparty_classification_id { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> country_residence_id { get; set; }
        public Nullable<int> country_risk_id { get; set; }
        public Nullable<int> country_control_id { get; set; }
        public Nullable<int> country_nationality_id { get; set; }
        public Nullable<int> country_registration_id { get; set; }
        public string registration_number { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public Nullable<int> counterparty_category_id { get; set; }
        public Nullable<bool> group { get; set; }
        public Nullable<int> relationship_manager_1_id { get; set; }
        public Nullable<int> relationship_manager_2_id { get; set; }
        public Nullable<int> relationship_manager_3_id { get; set; }
        public Nullable<int> industry_sector_1_id { get; set; }
        public Nullable<int> industry_sector_2_id { get; set; }
        public Nullable<int> industry_sector_3_id { get; set; }
        public Nullable<int> economic_sector_1_id { get; set; }
        public Nullable<int> economic_sector_2_id { get; set; }
        public Nullable<int> economic_sector_3_id { get; set; }
        public Nullable<System.DateTime> relationship_start_date { get; set; }
        public Nullable<decimal> turnover { get; set; }
        public Nullable<int> turnover_ccy_id { get; set; }
        public Nullable<decimal> total_asset { get; set; }
        public Nullable<int> total_asset_ccy { get; set; }
        public Nullable<int> employee { get; set; }
        public Nullable<System.DateTime> previous_review_date { get; set; }
        public Nullable<System.DateTime> next_review_date { get; set; }
        public string review_frequency { get; set; }
        public string employee_relation { get; set; }
        public Nullable<int> internal_rating_type_id { get; set; }
        public string credit_state { get; set; }
        public Nullable<bool> watchlist { get; set; }
        public Nullable<int> status_id { get; set; }
        public string external_reference { get; set; }
        public Nullable<bool> email_notification { get; set; }
        public Nullable<bool> sms_notification { get; set; }
        public Nullable<bool> fax_notification { get; set; }
        public Nullable<bool> phone_notification { get; set; }
        public Nullable<int> prospecting_status { get; set; }
        public string counterparty_ident { get; set; }
        public string counterparty_ident_type { get; set; }
        public Nullable<System.DateTime> ident_issuance_date { get; set; }
        public Nullable<System.DateTime> ident_expiry_date { get; set; }
        public string registration_place { get; set; }
        public string counterparty_ident2 { get; set; }
        public string counterparty_ident_type2 { get; set; }
        public Nullable<System.DateTime> ident_issuance_date2 { get; set; }
        public Nullable<System.DateTime> ident_expiry_date2 { get; set; }
        public string registration_place2 { get; set; }
        public string counterparty_ident3 { get; set; }
        public string counterparty_ident_type3 { get; set; }
        public Nullable<System.DateTime> ident_issuance_date3 { get; set; }
        public Nullable<System.DateTime> ident_expiry_date3 { get; set; }
        public string registration_place3 { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string marital_status { get; set; }
        public string counterparty_screen { get; set; }
        public string employer { get; set; }
        public Nullable<decimal> profit_margin { get; set; }
        public Nullable<int> profit_margin_ccy_id { get; set; }
        public string birth_place { get; set; }
        public string partner_type { get; set; }
        public string partner_first_name { get; set; }
        public string partner_last_name { get; set; }
        public Nullable<System.DateTime> partner_birth_date { get; set; }
        public Nullable<int> partner_counterparty_classification_id { get; set; }
        public Nullable<System.DateTime> partner_registration_date { get; set; }
        public Nullable<System.DateTime> credit_state_date { get; set; }
        public Nullable<int> account_type_id { get; set; }
        public string partner_employer { get; set; }
        public string partner_ident_type { get; set; }
        public string partner_ident { get; set; }
        public Nullable<bool> exempt { get; set; }
        public Nullable<decimal> credit_amount { get; set; }
        public Nullable<int> credit_amount_ccy_id { get; set; }
        public Nullable<int> counterparty_id1 { get; set; }
        public string counterparty_designation { get; set; }
        public string employment_status { get; set; }
        public string customer_profile { get; set; }
        public Nullable<int> kids_number { get; set; }
        public Nullable<int> residence_length { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string mobile2 { get; set; }
        public string phone2 { get; set; }
        public string email2 { get; set; }
        public string mobile3 { get; set; }
        public string phone3 { get; set; }
        public string email3 { get; set; }
        public Nullable<bool> activated { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string gender { get; set; }
    
        public virtual account_type account_type { get; set; }
        public virtual ICollection<accounting_output> accounting_output { get; set; }
        public virtual ICollection<accounting_output> accounting_output1 { get; set; }
        public virtual ICollection<accounting_output> accounting_output2 { get; set; }
        public virtual ICollection<bkt_discriminatory_history_detail> bkt_discriminatory_history_detail { get; set; }
        public virtual ICollection<bkt_lgd_history> bkt_lgd_history { get; set; }
        public virtual ICollection<bkt_pd_history_detail> bkt_pd_history_detail { get; set; }
        public virtual ICollection<core_banking> core_banking { get; set; }
        public virtual ICollection<counterparty_account> counterparty_account { get; set; }
        public virtual ICollection<counterparty_account> counterparty_account1 { get; set; }
        public virtual ICollection<counterparty_action> counterparty_action { get; set; }
        public virtual ICollection<counterparty_amount> counterparty_amount { get; set; }
        public virtual counterparty_comment counterparty_comment { get; set; }
        public virtual ICollection<counterparty_contacts> counterparty_contacts { get; set; }
        public virtual counterparty_category counterparty_category { get; set; }
        public virtual counterparty_classification counterparty_classification { get; set; }
        public virtual counterparty_type counterparty_type { get; set; }
        public virtual ICollection<counterparty> counterparty1 { get; set; }
        public virtual counterparty counterparty2 { get; set; }
        public virtual country country { get; set; }
        public virtual country country1 { get; set; }
        public virtual country country2 { get; set; }
        public virtual country country3 { get; set; }
        public virtual country country4 { get; set; }
        public virtual ICollection<counterparty_cpty> counterparty_cpty { get; set; }
        public virtual ICollection<counterparty_cpty> counterparty_cpty1 { get; set; }
        public virtual currency currency { get; set; }
        public virtual ICollection<counterparty_credit_state_history> counterparty_credit_state_history { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual currency currency2 { get; set; }
        public virtual economic_sector economic_sector { get; set; }
        public virtual economic_sector economic_sector1 { get; set; }
        public virtual economic_sector economic_sector2 { get; set; }
        public virtual ICollection<counterparty_external_rating> counterparty_external_rating { get; set; }
        public virtual ICollection<counterparty_financial_data> counterparty_financial_data { get; set; }
        public virtual ICollection<counterparty_financial_structure> counterparty_financial_structure { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic { get; set; }
        public virtual industry_sector industry_sector { get; set; }
        public virtual industry_sector industry_sector1 { get; set; }
        public virtual industry_sector industry_sector2 { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual ICollection<counterparty_internal_rating> counterparty_internal_rating { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<counterparty_parent> counterparty_parent { get; set; }
        public virtual ICollection<counterparty_parent> counterparty_parent1 { get; set; }
        public virtual counterparty_classification counterparty_classification1 { get; set; }
        public virtual currency currency3 { get; set; }
        public virtual ICollection<counterparty_qualitative_data> counterparty_qualitative_data { get; set; }
        public virtual ICollection<counterparty_qualitative_element> counterparty_qualitative_element { get; set; }
        public virtual ICollection<counterparty_qualitative_node> counterparty_qualitative_node { get; set; }
        public virtual rating_type rating_type { get; set; }
        public virtual scoring_template scoring_template { get; set; }
        public virtual ICollection<counterparty_shareholders> counterparty_shareholders { get; set; }
        public virtual software_user software_user { get; set; }
        public virtual software_user software_user1 { get; set; }
        public virtual software_user software_user2 { get; set; }
        public virtual status status { get; set; }
        public virtual status status1 { get; set; }
        public virtual ICollection<counterparty_user> counterparty_user { get; set; }
        public virtual ICollection<counterparty_address> counterparty_address { get; set; }
        public virtual ICollection<credit_file> credit_file { get; set; }
        public virtual ICollection<credit_file_cpty> credit_file_cpty { get; set; }
        public virtual ICollection<financial_analysis_session> financial_analysis_session { get; set; }
        public virtual ICollection<marketing_action> marketing_action { get; set; }
        public virtual ICollection<mitigant_participant> mitigant_participant { get; set; }
        public virtual ICollection<outstanding> outstanding { get; set; }
        public virtual ICollection<payment> payment { get; set; }
        public virtual ICollection<recovery_type_parameter_counterparty> recovery_type_parameter_counterparty { get; set; }
        public virtual ICollection<security> security { get; set; }
        public virtual ICollection<transaction_amount> transaction_amount { get; set; }
        public virtual ICollection<transaction_amount> transaction_amount1 { get; set; }
        public virtual ICollection<transaction> transaction { get; set; }
        public virtual ICollection<transaction_reallocation> transaction_reallocation { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery1 { get; set; }
    }
}
