//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_generic
    {
        public int counterparty_generic_id { get; set; }
        public int counterparty_id { get; set; }
        public Nullable<int> number_field1 { get; set; }
        public Nullable<int> number_field2 { get; set; }
        public Nullable<int> number_field3 { get; set; }
        public Nullable<int> number_field4 { get; set; }
        public Nullable<int> number_field5 { get; set; }
        public Nullable<int> number_field6 { get; set; }
        public Nullable<int> number_field7 { get; set; }
        public Nullable<int> number_field8 { get; set; }
        public Nullable<int> number_field9 { get; set; }
        public Nullable<int> number_field10 { get; set; }
        public Nullable<decimal> amount_field1 { get; set; }
        public Nullable<int> amount_field1_ccy { get; set; }
        public Nullable<decimal> amount_field2 { get; set; }
        public Nullable<int> amount_field2_ccy { get; set; }
        public Nullable<decimal> amount_field3 { get; set; }
        public Nullable<int> amount_field3_ccy { get; set; }
        public Nullable<decimal> amount_field4 { get; set; }
        public Nullable<int> amount_field4_ccy { get; set; }
        public Nullable<decimal> amount_field5 { get; set; }
        public Nullable<int> amount_field5_ccy { get; set; }
        public Nullable<decimal> amount_field6 { get; set; }
        public Nullable<int> amount_field6_ccy { get; set; }
        public Nullable<decimal> amount_field7 { get; set; }
        public Nullable<int> amount_field7_ccy { get; set; }
        public Nullable<decimal> amount_field8 { get; set; }
        public Nullable<int> amount_field8_ccy { get; set; }
        public Nullable<decimal> amount_field9 { get; set; }
        public Nullable<int> amount_field9_ccy { get; set; }
        public Nullable<decimal> amount_field10 { get; set; }
        public Nullable<int> amount_field10_ccy { get; set; }
        public string text_field1 { get; set; }
        public string text_field2 { get; set; }
        public string text_field3 { get; set; }
        public string text_field4 { get; set; }
        public string text_field5 { get; set; }
        public string text_field6 { get; set; }
        public string text_field7 { get; set; }
        public string text_field8 { get; set; }
        public string text_field9 { get; set; }
        public string text_field10 { get; set; }
        public string comment_field1 { get; set; }
        public string comment_field2 { get; set; }
        public string comment_field3 { get; set; }
        public string comment_field4 { get; set; }
        public string comment_field5 { get; set; }
        public Nullable<System.DateTime> date_field1 { get; set; }
        public Nullable<System.DateTime> date_field2 { get; set; }
        public Nullable<System.DateTime> date_field3 { get; set; }
        public Nullable<System.DateTime> date_field4 { get; set; }
        public Nullable<System.DateTime> date_field5 { get; set; }
        public Nullable<System.DateTime> date_field6 { get; set; }
        public Nullable<System.DateTime> date_field7 { get; set; }
        public Nullable<System.DateTime> date_field8 { get; set; }
        public Nullable<System.DateTime> date_field9 { get; set; }
        public Nullable<System.DateTime> date_field10 { get; set; }
        public string flag { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual currency currency { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual currency currency2 { get; set; }
        public virtual currency currency3 { get; set; }
        public virtual currency currency4 { get; set; }
        public virtual currency currency5 { get; set; }
        public virtual currency currency6 { get; set; }
        public virtual currency currency7 { get; set; }
        public virtual currency currency8 { get; set; }
        public virtual currency currency9 { get; set; }
    }
}
