//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_amount
    {
        public int counterparty_amount_id { get; set; }
        public string counterparty_amount_shortname { get; set; }
        public Nullable<int> counterparty_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> currency_id { get; set; }
        public string frequency { get; set; }
        public string direction { get; set; }
        public Nullable<int> tenor { get; set; }
        public Nullable<decimal> coefficient { get; set; }
        public string amount_type { get; set; }
        public Nullable<System.DateTime> counterparty_amount_start_date { get; set; }
        public Nullable<System.DateTime> amount_day { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual currency currency { get; set; }
    }
}
