//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_financial_data
    {
        public int counterparty_financial_data_id { get; set; }
        public int counterparty_id { get; set; }
        public int data_category_id { get; set; }
        public int data_type_id { get; set; }
        public int data_element_id { get; set; }
        public System.DateTime data_element_date { get; set; }
        public Nullable<decimal> data_element_value { get; set; }
        public Nullable<int> data_element_ccy_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual currency currency { get; set; }
    }
}
