//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_credit_state_history
    {
        public int counterparty_credit_state_history_id { get; set; }
        public int counterparty_id { get; set; }
        public int credit_state_id { get; set; }
        public System.DateTime credit_state_start_date { get; set; }
        public Nullable<System.DateTime> credit_state_end_date { get; set; }
        public int transaction_id { get; set; }
        public string comment { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual status status { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
