//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_account
    {
        public int counterparty_account_id { get; set; }
        public string counterparty_account_shortname { get; set; }
        public string counterparty_account_description { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<int> account_type_id { get; set; }
        public int counterparty_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> relationship_manager_id { get; set; }
        public Nullable<int> counterparty_account_bank { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<System.DateTime> balance_date { get; set; }
        public Nullable<bool> isdefault { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<decimal> amount1 { get; set; }
        public Nullable<int> amount1_ccy { get; set; }
        public Nullable<decimal> amount2 { get; set; }
        public Nullable<int> amount2_ccy { get; set; }
        public Nullable<decimal> amount3 { get; set; }
        public Nullable<int> amount3_ccy { get; set; }
        public Nullable<decimal> amount4 { get; set; }
        public Nullable<int> amount4_ccy { get; set; }
        public Nullable<decimal> amount5 { get; set; }
        public Nullable<int> amount5_ccy { get; set; }
    
        public virtual account_type account_type { get; set; }
        public virtual counterparty counterparty { get; set; }
        public virtual counterparty counterparty1 { get; set; }
        public virtual currency currency { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual currency currency2 { get; set; }
        public virtual currency currency3 { get; set; }
        public virtual currency currency4 { get; set; }
        public virtual currency currency5 { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual software_user software_user { get; set; }
    }
}
