//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_contacts
    {
        public int counterparty_contacts_id { get; set; }
        public string contact { get; set; }
        public string position { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string phone2 { get; set; }
        public string mobile2 { get; set; }
        public string email2 { get; set; }
        public string fax2 { get; set; }
        public string phone3 { get; set; }
        public string mobile3 { get; set; }
        public string email3 { get; set; }
        public string fax3 { get; set; }
        public Nullable<bool> signatory { get; set; }
        public string contact_ident_type { get; set; }
        public string contact_ident { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<bool> isdefault { get; set; }
        public int counterparty_id { get; set; }
        public string address { get; set; }
        public string address_type { get; set; }
        public string zip_code { get; set; }
        public string city { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> country_region_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual country country { get; set; }
        public virtual country_region country_region { get; set; }
    }
}
