//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_comment
    {
        public int counterparty_id { get; set; }
        public int counterparty_comment_id { get; set; }
        public string comment1 { get; set; }
        public string comment2 { get; set; }
        public string comment3 { get; set; }
        public string comment4 { get; set; }
        public string comment5 { get; set; }
        public string comment6 { get; set; }
        public string comment7 { get; set; }
        public string comment8 { get; set; }
        public string comment9 { get; set; }
        public string comment10 { get; set; }
        public string comment11 { get; set; }
        public string comment12 { get; set; }
        public string comment13 { get; set; }
        public string comment14 { get; set; }
        public string comment15 { get; set; }
        public string comment16 { get; set; }
        public string comment17 { get; set; }
        public string comment18 { get; set; }
        public string comment19 { get; set; }
        public string comment20 { get; set; }
        public string comment21 { get; set; }
        public string comment22 { get; set; }
        public string comment23 { get; set; }
        public string comment24 { get; set; }
        public string comment25 { get; set; }
        public string comment26 { get; set; }
        public string comment27 { get; set; }
        public string comment28 { get; set; }
        public string comment29 { get; set; }
        public string comment30 { get; set; }
    
        public virtual counterparty counterparty { get; set; }
    }
}
