//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_financial_structure
    {
        public int counterparty_id { get; set; }
        public int financial_structure_id { get; set; }
        public Nullable<int> financial_analysis_session_id { get; set; }
        public Nullable<decimal> financial_structure_value { get; set; }
        public Nullable<int> financial_structure_value_ccy_id { get; set; }
        public Nullable<int> scoring_session_id { get; set; }
        public string comment { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public int counterparty_financial_structure_id { get; set; }
        public Nullable<int> scoring_status_id { get; set; }
        public System.DateTime period { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual currency currency { get; set; }
        public virtual financial_analysis_session financial_analysis_session { get; set; }
        public virtual financial_structure financial_structure { get; set; }
        public virtual scoring_session scoring_session { get; set; }
    }
}
