//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class counterparty_action
    {
        public int counterparty_action_id { get; set; }
        public int counterparty_id { get; set; }
        public string action_type { get; set; }
        public Nullable<System.DateTime> action_date { get; set; }
        public string comment { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string contact { get; set; }
        public string expectation { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> amount_ccy { get; set; }
        public string manager { get; set; }
        public string purpose { get; set; }
        public string report { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual currency currency { get; set; }
    }
}
