//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class covenant
    {
        public covenant()
        {
            this.credit_file_covenant = new HashSet<credit_file_covenant>();
            this.transaction_covenant = new HashSet<transaction_covenant>();
        }
    
        public int covenant_id { get; set; }
        public string financial_covenant_shortname { get; set; }
        public string financial_covenant_description { get; set; }
        public string comment { get; set; }
        public Nullable<int> financial_structure_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual financial_structure financial_structure { get; set; }
        public virtual ICollection<credit_file_covenant> credit_file_covenant { get; set; }
        public virtual ICollection<transaction_covenant> transaction_covenant { get; set; }
    }
}
