//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit_file
    {
        public credit_file()
        {
            this.credit_file_condition = new HashSet<credit_file_condition>();
            this.credit_file_covenant = new HashSet<credit_file_covenant>();
            this.credit_file_cpty = new HashSet<credit_file_cpty>();
            this.credit_file_generic = new HashSet<credit_file_generic>();
            this.credit_file_mitigant = new HashSet<credit_file_mitigant>();
            this.credit_file_user = new HashSet<credit_file_user>();
            this.credit_file_opinion = new HashSet<credit_file_opinion>();
            this.credit_file_rating = new HashSet<credit_file_rating>();
            this.credit_file_transaction = new HashSet<credit_file_transaction>();
        }
    
        public int credit_file_id { get; set; }
        public string credit_file_shortname { get; set; }
        public string credit_file_name { get; set; }
        public string credit_file_desc { get; set; }
        public Nullable<int> counterparty_id { get; set; }
        public Nullable<int> transaction_type_id { get; set; }
        public Nullable<bool> children_cpty_included { get; set; }
        public string credit_file_category { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> manager_id1 { get; set; }
        public Nullable<System.DateTime> application_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<System.DateTime> previous_review_date { get; set; }
        public Nullable<System.DateTime> next_review_date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> amount_ccy_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string emergency { get; set; }
        public string purpose { get; set; }
        public string purpose_description { get; set; }
        public Nullable<int> manager_id2 { get; set; }
        public Nullable<int> manager_id3 { get; set; }
        public Nullable<int> manager_id4 { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual credit_file_comment credit_file_comment { get; set; }
        public virtual ICollection<credit_file_condition> credit_file_condition { get; set; }
        public virtual ICollection<credit_file_covenant> credit_file_covenant { get; set; }
        public virtual ICollection<credit_file_cpty> credit_file_cpty { get; set; }
        public virtual currency currency { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<credit_file_mitigant> credit_file_mitigant { get; set; }
        public virtual ICollection<credit_file_user> credit_file_user { get; set; }
        public virtual ICollection<credit_file_opinion> credit_file_opinion { get; set; }
        public virtual ICollection<credit_file_rating> credit_file_rating { get; set; }
        public virtual software_user software_user { get; set; }
        public virtual software_user software_user1 { get; set; }
        public virtual software_user software_user2 { get; set; }
        public virtual software_user software_user3 { get; set; }
        public virtual status status { get; set; }
        public virtual ICollection<credit_file_transaction> credit_file_transaction { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
