//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit_file_cpty
    {
        public int credit_file_cpty_id { get; set; }
        public int credit_file_id { get; set; }
        public int counterparty_id { get; set; }
        public string counterparty_role { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual credit_file credit_file { get; set; }
        public virtual currency currency { get; set; }
    }
}
