//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit_file_mitigant
    {
        public int credit_file_mitigant_id { get; set; }
        public int credit_file_id { get; set; }
        public int mitigant_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> status_id { get; set; }
        public string comment { get; set; }
    
        public virtual credit_file credit_file { get; set; }
        public virtual mitigant mitigant { get; set; }
        public virtual status status { get; set; }
    }
}
