//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public currency()
        {
            this.accounting_output = new HashSet<accounting_output>();
            this.commodity = new HashSet<commodity>();
            this.commodity_quote = new HashSet<commodity_quote>();
            this.core_banking = new HashSet<core_banking>();
            this.counterparty = new HashSet<counterparty>();
            this.counterparty1 = new HashSet<counterparty>();
            this.counterparty2 = new HashSet<counterparty>();
            this.counterparty3 = new HashSet<counterparty>();
            this.counterparty_account = new HashSet<counterparty_account>();
            this.counterparty_account1 = new HashSet<counterparty_account>();
            this.counterparty_account2 = new HashSet<counterparty_account>();
            this.counterparty_account3 = new HashSet<counterparty_account>();
            this.counterparty_account4 = new HashSet<counterparty_account>();
            this.counterparty_account5 = new HashSet<counterparty_account>();
            this.counterparty_action = new HashSet<counterparty_action>();
            this.counterparty_add_data = new HashSet<counterparty_add_data>();
            this.counterparty_add_data_litigation = new HashSet<counterparty_add_data_litigation>();
            this.counterparty_amount = new HashSet<counterparty_amount>();
            this.counterparty_financial_data = new HashSet<counterparty_financial_data>();
            this.counterparty_financial_structure = new HashSet<counterparty_financial_structure>();
            this.counterparty_generic = new HashSet<counterparty_generic>();
            this.counterparty_generic1 = new HashSet<counterparty_generic>();
            this.counterparty_generic2 = new HashSet<counterparty_generic>();
            this.counterparty_generic3 = new HashSet<counterparty_generic>();
            this.counterparty_generic4 = new HashSet<counterparty_generic>();
            this.counterparty_generic5 = new HashSet<counterparty_generic>();
            this.counterparty_generic6 = new HashSet<counterparty_generic>();
            this.counterparty_generic7 = new HashSet<counterparty_generic>();
            this.counterparty_generic8 = new HashSet<counterparty_generic>();
            this.counterparty_generic9 = new HashSet<counterparty_generic>();
            this.counterparty_shareholders = new HashSet<counterparty_shareholders>();
            this.country = new HashSet<country>();
            this.credit_file = new HashSet<credit_file>();
            this.credit_file_add_data = new HashSet<credit_file_add_data>();
            this.credit_file_condition = new HashSet<credit_file_condition>();
            this.credit_file_condition1 = new HashSet<credit_file_condition>();
            this.credit_file_condition2 = new HashSet<credit_file_condition>();
            this.credit_file_condition3 = new HashSet<credit_file_condition>();
            this.credit_file_condition_fees = new HashSet<credit_file_condition_fees>();
            this.credit_file_covenant = new HashSet<credit_file_covenant>();
            this.credit_file_cpty = new HashSet<credit_file_cpty>();
            this.credit_file_generic = new HashSet<credit_file_generic>();
            this.credit_file_generic1 = new HashSet<credit_file_generic>();
            this.credit_file_generic2 = new HashSet<credit_file_generic>();
            this.credit_file_generic3 = new HashSet<credit_file_generic>();
            this.credit_file_generic4 = new HashSet<credit_file_generic>();
            this.credit_file_generic5 = new HashSet<credit_file_generic>();
            this.credit_file_generic6 = new HashSet<credit_file_generic>();
            this.credit_file_generic7 = new HashSet<credit_file_generic>();
            this.credit_file_generic8 = new HashSet<credit_file_generic>();
            this.credit_file_generic9 = new HashSet<credit_file_generic>();
            this.currency_exchange_rate = new HashSet<currency_exchange_rate>();
            this.lgd_result = new HashSet<lgd_result>();
            this.mitigant_add_data = new HashSet<mitigant_add_data>();
            this.mitigant_collateral = new HashSet<mitigant_collateral>();
            this.mitigant_collateral1 = new HashSet<mitigant_collateral>();
            this.mitigant_collateral2 = new HashSet<mitigant_collateral>();
            this.mitigant_collateral3 = new HashSet<mitigant_collateral>();
            this.mitigant_collateral4 = new HashSet<mitigant_collateral>();
            this.mitigant = new HashSet<mitigant>();
            this.mitigant1 = new HashSet<mitigant>();
            this.mitigant2 = new HashSet<mitigant>();
            this.mitigant3 = new HashSet<mitigant>();
            this.mitigant4 = new HashSet<mitigant>();
            this.mitigant_generic = new HashSet<mitigant_generic>();
            this.mitigant_generic1 = new HashSet<mitigant_generic>();
            this.mitigant_generic2 = new HashSet<mitigant_generic>();
            this.mitigant_generic3 = new HashSet<mitigant_generic>();
            this.mitigant_generic4 = new HashSet<mitigant_generic>();
            this.mitigant_generic5 = new HashSet<mitigant_generic>();
            this.mitigant_generic6 = new HashSet<mitigant_generic>();
            this.mitigant_generic7 = new HashSet<mitigant_generic>();
            this.mitigant_generic8 = new HashSet<mitigant_generic>();
            this.mitigant_generic9 = new HashSet<mitigant_generic>();
            this.mitigant_participant = new HashSet<mitigant_participant>();
            this.mitigant_transaction = new HashSet<mitigant_transaction>();
            this.mitigant_valuation = new HashSet<mitigant_valuation>();
            this.outstanding = new HashSet<outstanding>();
            this.outstanding1 = new HashSet<outstanding>();
            this.outstanding2 = new HashSet<outstanding>();
            this.outstanding3 = new HashSet<outstanding>();
            this.outstanding4 = new HashSet<outstanding>();
            this.payment = new HashSet<payment>();
            this.payment1 = new HashSet<payment>();
            this.payment2 = new HashSet<payment>();
            this.payment_posting = new HashSet<payment_posting>();
            this.pricing_condition = new HashSet<pricing_condition>();
            this.pricing_condition_fees = new HashSet<pricing_condition_fees>();
            this.recovery_arrangement_action = new HashSet<recovery_arrangement_action>();
            this.security = new HashSet<security>();
            this.security_quote = new HashSet<security_quote>();
            this.specific_agreement = new HashSet<specific_agreement>();
            this.strategy = new HashSet<strategy>();
            this.transaction_condition_tier = new HashSet<transaction_condition_tier>();
            this.transaction_add_data = new HashSet<transaction_add_data>();
            this.transaction_amount = new HashSet<transaction_amount>();
            this.transaction_amount_fees = new HashSet<transaction_amount_fees>();
            this.transaction_condition = new HashSet<transaction_condition>();
            this.transaction_condition1 = new HashSet<transaction_condition>();
            this.transaction_condition2 = new HashSet<transaction_condition>();
            this.transaction_condition3 = new HashSet<transaction_condition>();
            this.transaction_condition4 = new HashSet<transaction_condition>();
            this.transaction_condition_fees = new HashSet<transaction_condition_fees>();
            this.transaction_condition_tier1 = new HashSet<transaction_condition_tier>();
            this.transaction_condition_tier2 = new HashSet<transaction_condition_tier>();
            this.transaction_condition_tier3 = new HashSet<transaction_condition_tier>();
            this.transaction_condition_tier4 = new HashSet<transaction_condition_tier>();
            this.transaction_condition_tier5 = new HashSet<transaction_condition_tier>();
            this.transaction_condition_tier6 = new HashSet<transaction_condition_tier>();
            this.transaction = new HashSet<transaction>();
            this.transaction1 = new HashSet<transaction>();
            this.transaction_covenant = new HashSet<transaction_covenant>();
            this.transaction_covenant_history = new HashSet<transaction_covenant_history>();
            this.transaction_cpty = new HashSet<transaction_cpty>();
            this.transaction_cpty1 = new HashSet<transaction_cpty>();
            this.transaction_credit_event = new HashSet<transaction_credit_event>();
            this.transaction_credit_event1 = new HashSet<transaction_credit_event>();
            this.transaction_credit_event2 = new HashSet<transaction_credit_event>();
            this.transaction_credit_event3 = new HashSet<transaction_credit_event>();
            this.transaction2 = new HashSet<transaction>();
            this.transaction3 = new HashSet<transaction>();
            this.transaction4 = new HashSet<transaction>();
            this.transaction5 = new HashSet<transaction>();
            this.transaction6 = new HashSet<transaction>();
            this.transaction7 = new HashSet<transaction>();
            this.transaction8 = new HashSet<transaction>();
            this.transaction9 = new HashSet<transaction>();
            this.transaction10 = new HashSet<transaction>();
            this.transaction11 = new HashSet<transaction>();
            this.transaction12 = new HashSet<transaction>();
            this.transaction_generic = new HashSet<transaction_generic>();
            this.transaction_generic1 = new HashSet<transaction_generic>();
            this.transaction_generic2 = new HashSet<transaction_generic>();
            this.transaction_generic3 = new HashSet<transaction_generic>();
            this.transaction_generic4 = new HashSet<transaction_generic>();
            this.transaction_generic5 = new HashSet<transaction_generic>();
            this.transaction_generic6 = new HashSet<transaction_generic>();
            this.transaction_generic7 = new HashSet<transaction_generic>();
            this.transaction_generic8 = new HashSet<transaction_generic>();
            this.transaction_generic9 = new HashSet<transaction_generic>();
            this.transaction13 = new HashSet<transaction>();
            this.transaction_limit_monitoring = new HashSet<transaction_limit_monitoring>();
            this.transaction_reallocation = new HashSet<transaction_reallocation>();
            this.transaction_reallocation1 = new HashSet<transaction_reallocation>();
            this.transaction_recovery = new HashSet<transaction_recovery>();
            this.transaction_recovery1 = new HashSet<transaction_recovery>();
            this.transaction_recovery2 = new HashSet<transaction_recovery>();
            this.transaction_recovery3 = new HashSet<transaction_recovery>();
            this.transaction_recovery_mitigant = new HashSet<transaction_recovery_mitigant>();
            this.transaction_recovery4 = new HashSet<transaction_recovery>();
            this.transaction_related_utilizations = new HashSet<transaction_related_utilizations>();
            this.transaction14 = new HashSet<transaction>();
            this.transaction_type = new HashSet<transaction_type>();
            this.transaction_type_fees = new HashSet<transaction_type_fees>();
        }
    
        public int currency_id { get; set; }
        public string currency_shortname { get; set; }
        public string currency_name { get; set; }
        public string currency_group { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<accounting_output> accounting_output { get; set; }
        public virtual ICollection<commodity> commodity { get; set; }
        public virtual ICollection<commodity_quote> commodity_quote { get; set; }
        public virtual ICollection<core_banking> core_banking { get; set; }
        public virtual ICollection<counterparty> counterparty { get; set; }
        public virtual ICollection<counterparty> counterparty1 { get; set; }
        public virtual ICollection<counterparty> counterparty2 { get; set; }
        public virtual ICollection<counterparty> counterparty3 { get; set; }
        public virtual ICollection<counterparty_account> counterparty_account { get; set; }
        public virtual ICollection<counterparty_account> counterparty_account1 { get; set; }
        public virtual ICollection<counterparty_account> counterparty_account2 { get; set; }
        public virtual ICollection<counterparty_account> counterparty_account3 { get; set; }
        public virtual ICollection<counterparty_account> counterparty_account4 { get; set; }
        public virtual ICollection<counterparty_account> counterparty_account5 { get; set; }
        public virtual ICollection<counterparty_action> counterparty_action { get; set; }
        public virtual ICollection<counterparty_add_data> counterparty_add_data { get; set; }
        public virtual ICollection<counterparty_add_data_litigation> counterparty_add_data_litigation { get; set; }
        public virtual ICollection<counterparty_amount> counterparty_amount { get; set; }
        public virtual ICollection<counterparty_financial_data> counterparty_financial_data { get; set; }
        public virtual ICollection<counterparty_financial_structure> counterparty_financial_structure { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic1 { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic2 { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic3 { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic4 { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic5 { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic6 { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic7 { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic8 { get; set; }
        public virtual ICollection<counterparty_generic> counterparty_generic9 { get; set; }
        public virtual ICollection<counterparty_shareholders> counterparty_shareholders { get; set; }
        public virtual ICollection<country> country { get; set; }
        public virtual ICollection<credit_file> credit_file { get; set; }
        public virtual ICollection<credit_file_add_data> credit_file_add_data { get; set; }
        public virtual ICollection<credit_file_condition> credit_file_condition { get; set; }
        public virtual ICollection<credit_file_condition> credit_file_condition1 { get; set; }
        public virtual ICollection<credit_file_condition> credit_file_condition2 { get; set; }
        public virtual ICollection<credit_file_condition> credit_file_condition3 { get; set; }
        public virtual ICollection<credit_file_condition_fees> credit_file_condition_fees { get; set; }
        public virtual ICollection<credit_file_covenant> credit_file_covenant { get; set; }
        public virtual ICollection<credit_file_cpty> credit_file_cpty { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic1 { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic2 { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic3 { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic4 { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic5 { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic6 { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic7 { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic8 { get; set; }
        public virtual ICollection<credit_file_generic> credit_file_generic9 { get; set; }
        public virtual ICollection<currency_exchange_rate> currency_exchange_rate { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<lgd_result> lgd_result { get; set; }
        public virtual ICollection<mitigant_add_data> mitigant_add_data { get; set; }
        public virtual ICollection<mitigant_collateral> mitigant_collateral { get; set; }
        public virtual ICollection<mitigant_collateral> mitigant_collateral1 { get; set; }
        public virtual ICollection<mitigant_collateral> mitigant_collateral2 { get; set; }
        public virtual ICollection<mitigant_collateral> mitigant_collateral3 { get; set; }
        public virtual ICollection<mitigant_collateral> mitigant_collateral4 { get; set; }
        public virtual ICollection<mitigant> mitigant { get; set; }
        public virtual ICollection<mitigant> mitigant1 { get; set; }
        public virtual ICollection<mitigant> mitigant2 { get; set; }
        public virtual ICollection<mitigant> mitigant3 { get; set; }
        public virtual ICollection<mitigant> mitigant4 { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic1 { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic2 { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic3 { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic4 { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic5 { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic6 { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic7 { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic8 { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic9 { get; set; }
        public virtual ICollection<mitigant_participant> mitigant_participant { get; set; }
        public virtual ICollection<mitigant_transaction> mitigant_transaction { get; set; }
        public virtual ICollection<mitigant_valuation> mitigant_valuation { get; set; }
        public virtual ICollection<outstanding> outstanding { get; set; }
        public virtual ICollection<outstanding> outstanding1 { get; set; }
        public virtual ICollection<outstanding> outstanding2 { get; set; }
        public virtual ICollection<outstanding> outstanding3 { get; set; }
        public virtual ICollection<outstanding> outstanding4 { get; set; }
        public virtual ICollection<payment> payment { get; set; }
        public virtual ICollection<payment> payment1 { get; set; }
        public virtual ICollection<payment> payment2 { get; set; }
        public virtual ICollection<payment_posting> payment_posting { get; set; }
        public virtual ICollection<pricing_condition> pricing_condition { get; set; }
        public virtual ICollection<pricing_condition_fees> pricing_condition_fees { get; set; }
        public virtual ICollection<recovery_arrangement_action> recovery_arrangement_action { get; set; }
        public virtual ICollection<security> security { get; set; }
        public virtual ICollection<security_quote> security_quote { get; set; }
        public virtual ICollection<specific_agreement> specific_agreement { get; set; }
        public virtual ICollection<strategy> strategy { get; set; }
        public virtual ICollection<transaction_condition_tier> transaction_condition_tier { get; set; }
        public virtual ICollection<transaction_add_data> transaction_add_data { get; set; }
        public virtual ICollection<transaction_amount> transaction_amount { get; set; }
        public virtual ICollection<transaction_amount_fees> transaction_amount_fees { get; set; }
        public virtual ICollection<transaction_condition> transaction_condition { get; set; }
        public virtual ICollection<transaction_condition> transaction_condition1 { get; set; }
        public virtual ICollection<transaction_condition> transaction_condition2 { get; set; }
        public virtual ICollection<transaction_condition> transaction_condition3 { get; set; }
        public virtual ICollection<transaction_condition> transaction_condition4 { get; set; }
        public virtual ICollection<transaction_condition_fees> transaction_condition_fees { get; set; }
        public virtual ICollection<transaction_condition_tier> transaction_condition_tier1 { get; set; }
        public virtual ICollection<transaction_condition_tier> transaction_condition_tier2 { get; set; }
        public virtual ICollection<transaction_condition_tier> transaction_condition_tier3 { get; set; }
        public virtual ICollection<transaction_condition_tier> transaction_condition_tier4 { get; set; }
        public virtual ICollection<transaction_condition_tier> transaction_condition_tier5 { get; set; }
        public virtual ICollection<transaction_condition_tier> transaction_condition_tier6 { get; set; }
        public virtual ICollection<transaction> transaction { get; set; }
        public virtual ICollection<transaction> transaction1 { get; set; }
        public virtual ICollection<transaction_covenant> transaction_covenant { get; set; }
        public virtual ICollection<transaction_covenant_history> transaction_covenant_history { get; set; }
        public virtual ICollection<transaction_cpty> transaction_cpty { get; set; }
        public virtual ICollection<transaction_cpty> transaction_cpty1 { get; set; }
        public virtual ICollection<transaction_credit_event> transaction_credit_event { get; set; }
        public virtual ICollection<transaction_credit_event> transaction_credit_event1 { get; set; }
        public virtual ICollection<transaction_credit_event> transaction_credit_event2 { get; set; }
        public virtual ICollection<transaction_credit_event> transaction_credit_event3 { get; set; }
        public virtual ICollection<transaction> transaction2 { get; set; }
        public virtual ICollection<transaction> transaction3 { get; set; }
        public virtual ICollection<transaction> transaction4 { get; set; }
        public virtual ICollection<transaction> transaction5 { get; set; }
        public virtual ICollection<transaction> transaction6 { get; set; }
        public virtual ICollection<transaction> transaction7 { get; set; }
        public virtual ICollection<transaction> transaction8 { get; set; }
        public virtual ICollection<transaction> transaction9 { get; set; }
        public virtual ICollection<transaction> transaction10 { get; set; }
        public virtual ICollection<transaction> transaction11 { get; set; }
        public virtual ICollection<transaction> transaction12 { get; set; }
        public virtual ICollection<transaction_generic> transaction_generic { get; set; }
        public virtual ICollection<transaction_generic> transaction_generic1 { get; set; }
        public virtual ICollection<transaction_generic> transaction_generic2 { get; set; }
        public virtual ICollection<transaction_generic> transaction_generic3 { get; set; }
        public virtual ICollection<transaction_generic> transaction_generic4 { get; set; }
        public virtual ICollection<transaction_generic> transaction_generic5 { get; set; }
        public virtual ICollection<transaction_generic> transaction_generic6 { get; set; }
        public virtual ICollection<transaction_generic> transaction_generic7 { get; set; }
        public virtual ICollection<transaction_generic> transaction_generic8 { get; set; }
        public virtual ICollection<transaction_generic> transaction_generic9 { get; set; }
        public virtual ICollection<transaction> transaction13 { get; set; }
        public virtual ICollection<transaction_limit_monitoring> transaction_limit_monitoring { get; set; }
        public virtual ICollection<transaction_reallocation> transaction_reallocation { get; set; }
        public virtual ICollection<transaction_reallocation> transaction_reallocation1 { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery1 { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery2 { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery3 { get; set; }
        public virtual ICollection<transaction_recovery_mitigant> transaction_recovery_mitigant { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery4 { get; set; }
        public virtual ICollection<transaction_related_utilizations> transaction_related_utilizations { get; set; }
        public virtual ICollection<transaction> transaction14 { get; set; }
        public virtual ICollection<transaction_type> transaction_type { get; set; }
        public virtual ICollection<transaction_type_fees> transaction_type_fees { get; set; }
    }
}
