//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_category
    {
        public document_category()
        {
            this.document_sub_category = new HashSet<document_sub_category>();
        }
    
        public int document_category_id { get; set; }
        public string document_category_shortname { get; set; }
        public string document_category_item { get; set; }
        public string document_category_item_group_table { get; set; }
        public string document_category_item_group_field { get; set; }
        public Nullable<int> document_category_item_group_field_id { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<document_sub_category> document_sub_category { get; set; }
    }
}
