//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class economic_sector
    {
        public economic_sector()
        {
            this.counterparty = new HashSet<counterparty>();
            this.counterparty1 = new HashSet<counterparty>();
            this.counterparty2 = new HashSet<counterparty>();
            this.economic_sector_parent = new HashSet<economic_sector_parent>();
            this.economic_sector_parent1 = new HashSet<economic_sector_parent>();
        }
    
        public int economic_sector_id { get; set; }
        public string economic_sector_shortname { get; set; }
        public string economic_sector_name { get; set; }
        public string external_reference { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<counterparty> counterparty { get; set; }
        public virtual ICollection<counterparty> counterparty1 { get; set; }
        public virtual ICollection<counterparty> counterparty2 { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<economic_sector_parent> economic_sector_parent { get; set; }
        public virtual ICollection<economic_sector_parent> economic_sector_parent1 { get; set; }
    }
}
