//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class eligibility_criteria
    {
        public int eligibility_criteria_id { get; set; }
        public string eligibility_criteria_name { get; set; }
        public Nullable<int> criteria_field_id { get; set; }
        public string operat { get; set; }
        public string eligibility_criteria_value { get; set; }
        public Nullable<int> eligibility_condition_id { get; set; }
        public string left_parenthese { get; set; }
        public string right_parenthese { get; set; }
        public Nullable<int> eligibility_criteria_number { get; set; }
        public string audit_screen { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> duser { get; set; }
    
        public virtual criteria_field criteria_field { get; set; }
        public virtual eligibility_condition eligibility_condition { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
    }
}
