//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class eligibility_condition
    {
        public eligibility_condition()
        {
            this.decision_tree_eligibility = new HashSet<decision_tree_eligibility>();
            this.eligibility_condition1 = new HashSet<eligibility_condition>();
            this.eligibility_criteria = new HashSet<eligibility_criteria>();
            this.log_deviation = new HashSet<log_deviation>();
            this.transaction_type_eligibility_condition = new HashSet<transaction_type_eligibility_condition>();
        }
    
        public int eligibility_condition_id { get; set; }
        public string eligibility_condition_name { get; set; }
        public Nullable<bool> eligibility_condition_deviation { get; set; }
        public string eligibility_condition_error_msg { get; set; }
        public Nullable<int> transaction_type_id { get; set; }
        public string method { get; set; }
        public Nullable<int> pricing_condition_id { get; set; }
        public Nullable<bool> eligibility_condition_activated { get; set; }
        public string eligibility_condition_type { get; set; }
        public Nullable<int> eligibility_condition_parent_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> duser { get; set; }
        public string pricing_condition_sp { get; set; }
    
        public virtual ICollection<decision_tree_eligibility> decision_tree_eligibility { get; set; }
        public virtual transaction_type transaction_type { get; set; }
        public virtual ICollection<eligibility_condition> eligibility_condition1 { get; set; }
        public virtual eligibility_condition eligibility_condition2 { get; set; }
        public virtual pricing_condition pricing_condition { get; set; }
        public virtual ICollection<eligibility_criteria> eligibility_criteria { get; set; }
        public virtual ICollection<log_deviation> log_deviation { get; set; }
        public virtual ICollection<transaction_type_eligibility_condition> transaction_type_eligibility_condition { get; set; }
    }
}
