//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class fields_access_right_mc
    {
        public int sequence_id { get; set; }
        public Nullable<int> fields_access_right_id { get; set; }
        public string field_shortname { get; set; }
        public string display { get; set; }
        public int screen_id { get; set; }
        public int profile_id { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<bool> visible { get; set; }
    
        public virtual profile profile { get; set; }
        public virtual screen screen { get; set; }
    }
}
