//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class financial_data_category
    {
        public financial_data_category()
        {
            this.financial_data_forecast_formula = new HashSet<financial_data_forecast_formula>();
            this.financial_data_formula = new HashSet<financial_data_formula>();
            this.financial_data_structure = new HashSet<financial_data_structure>();
        }
    
        public int data_category_id { get; set; }
        public string data_category_shortname { get; set; }
        public string data_category_name { get; set; }
        public string data_category_type { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<financial_data_forecast_formula> financial_data_forecast_formula { get; set; }
        public virtual ICollection<financial_data_formula> financial_data_formula { get; set; }
        public virtual ICollection<financial_data_structure> financial_data_structure { get; set; }
    }
}
