//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class financial_template
    {
        public financial_template()
        {
            this.financial_forecasting = new HashSet<financial_forecasting>();
            this.financial_structure = new HashSet<financial_structure>();
        }
    
        public int financial_template_id { get; set; }
        public int financial_template_version { get; set; }
        public string financial_template_shortname { get; set; }
        public string financial_template_description { get; set; }
        public string item_type { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<bool> scoring { get; set; }
        public Nullable<int> periodicity { get; set; }
        public string condition { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<bool> manual_forecasting { get; set; }
    
        public virtual ICollection<financial_forecasting> financial_forecasting { get; set; }
        public virtual ICollection<financial_structure> financial_structure { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
    }
}
