//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class financial_analysis_session
    {
        public financial_analysis_session()
        {
            this.counterparty_financial_structure = new HashSet<counterparty_financial_structure>();
        }
    
        public Nullable<int> counterparty_id { get; set; }
        public Nullable<int> periodicity { get; set; }
        public Nullable<System.DateTime> financial_analysis_date { get; set; }
        public Nullable<int> status_id { get; set; }
        public string financial_analysis_comment { get; set; }
        public string forecast_comment { get; set; }
        public string benchmarking_comment { get; set; }
        public string stress_testing_comment { get; set; }
        public string peer_analysis_comment { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> financial_template_id { get; set; }
        public Nullable<int> financial_template_version { get; set; }
        public int financial_analysis_session_id { get; set; }
        public Nullable<int> scoring_template_id { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual ICollection<counterparty_financial_structure> counterparty_financial_structure { get; set; }
        public virtual scoring_template scoring_template { get; set; }
        public virtual status status { get; set; }
    }
}
