//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class financial_node
    {
        public financial_node()
        {
            this.financial_structure = new HashSet<financial_structure>();
            this.financial_structure1 = new HashSet<financial_structure>();
        }
    
        public int financial_node_id { get; set; }
        public string financial_node_shortname { get; set; }
        public string financial_node_name { get; set; }
        public string financial_node_display_format { get; set; }
        public Nullable<bool> peer_analysis { get; set; }
        public Nullable<decimal> peer_analysis_margin { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<financial_structure> financial_structure { get; set; }
        public virtual ICollection<financial_structure> financial_structure1 { get; set; }
    }
}
