//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class html_to_image
    {
        public int sequence_id { get; set; }
        public string entity { get; set; }
        public int item_id { get; set; }
        public string property { get; set; }
        public byte[] value { get; set; }
    }
}
