//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class industry_sector
    {
        public industry_sector()
        {
            this.counterparty = new HashSet<counterparty>();
            this.counterparty1 = new HashSet<counterparty>();
            this.counterparty2 = new HashSet<counterparty>();
            this.financial_data_model = new HashSet<financial_data_model>();
            this.industry_sector_parent = new HashSet<industry_sector_parent>();
        }
    
        public int industry_sector_id { get; set; }
        public string industry_sector_shortname { get; set; }
        public string industry_sector_name { get; set; }
        public string external_reference { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<counterparty> counterparty { get; set; }
        public virtual ICollection<counterparty> counterparty1 { get; set; }
        public virtual ICollection<counterparty> counterparty2 { get; set; }
        public virtual ICollection<financial_data_model> financial_data_model { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<industry_sector_parent> industry_sector_parent { get; set; }
    }
}
