//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class @interface
    {
        public int interface_id { get; set; }
        public Nullable<System.DateTime> Interface_date { get; set; }
        public string Interface_Type { get; set; }
        public string msgout { get; set; }
        public string msgin { get; set; }
        public string interface_status { get; set; }
        public string interface_error { get; set; }
        public string item_type { get; set; }
        public string item_id { get; set; }
        public string extref_sent { get; set; }
        public string extref_received { get; set; }
    }
}
