//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class interface_WS
    {
        public int interface_id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> interface_date { get; set; }
        public Nullable<bool> is_interfaced { get; set; }
    }
}
