//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class internal_segment
    {
        public internal_segment()
        {
            this.account_type = new HashSet<account_type>();
            this.action_type = new HashSet<action_type>();
            this.additional_data = new HashSet<additional_data>();
            this.aggregation_criteria = new HashSet<aggregation_criteria>();
            this.amortization_type = new HashSet<amortization_type>();
            this.arrangement_type = new HashSet<arrangement_type>();
            this.asset_class = new HashSet<asset_class>();
            this.base_rate = new HashSet<base_rate>();
            this.collateral_type = new HashSet<collateral_type>();
            this.combinaison_hierarchy_criteria_1 = new HashSet<combinaison_hierarchy_criteria_1>();
            this.combinaison_hierarchy_criteria_2 = new HashSet<combinaison_hierarchy_criteria_2>();
            this.combinaison_hierarchy_criteria_3 = new HashSet<combinaison_hierarchy_criteria_3>();
            this.combinaison_hierarchy_criteria_4 = new HashSet<combinaison_hierarchy_criteria_4>();
            this.commodity = new HashSet<commodity>();
            this.constants = new HashSet<constants>();
            this.counterparty = new HashSet<counterparty>();
            this.counterparty_add_data = new HashSet<counterparty_add_data>();
            this.counterparty_type = new HashSet<counterparty_type>();
            this.country = new HashSet<country>();
            this.country_group = new HashSet<country_group>();
            this.credit_event_type = new HashSet<credit_event_type>();
            this.credit_file = new HashSet<credit_file>();
            this.credit_file_add_data = new HashSet<credit_file_add_data>();
            this.criteria_field = new HashSet<criteria_field>();
            this.currency = new HashSet<currency>();
            this.decision_tree_eligibility = new HashSet<decision_tree_eligibility>();
            this.document_category = new HashSet<document_category>();
            this.economic_sector = new HashSet<economic_sector>();
            this.economic_sector_parent = new HashSet<economic_sector_parent>();
            this.eligibility_criteria = new HashSet<eligibility_criteria>();
            this.eligibility_criteria_fields = new HashSet<eligibility_criteria_fields>();
            this.email_out = new HashSet<email_out>();
            this.enforcing_log = new HashSet<enforcing_log>();
            this.estimated_probabilities = new HashSet<estimated_probabilities>();
            this.exposure = new HashSet<exposure>();
            this.exposure_real_time = new HashSet<exposure_real_time>();
            this.financial_benchmark = new HashSet<financial_benchmark>();
            this.financial_data_category = new HashSet<financial_data_category>();
            this.financial_data_element = new HashSet<financial_data_element>();
            this.financial_data_model = new HashSet<financial_data_model>();
            this.financial_data_type = new HashSet<financial_data_type>();
            this.financial_element = new HashSet<financial_element>();
            this.financial_forecast_scenario = new HashSet<financial_forecast_scenario>();
            this.financial_forecasting = new HashSet<financial_forecasting>();
            this.financial_node = new HashSet<financial_node>();
            this.financial_stress_scenario = new HashSet<financial_stress_scenario>();
            this.financial_template = new HashSet<financial_template>();
            this.folder_structuring = new HashSet<folder_structuring>();
            this.group = new HashSet<group>();
            this.group_access_right = new HashSet<group_access_right>();
            this.group_access_right_mc = new HashSet<group_access_right_mc>();
            this.group_mc = new HashSet<group_mc>();
            this.holidays_config = new HashSet<holidays_config>();
            this.industry_sector = new HashSet<industry_sector>();
            this.industry_sector_parent = new HashSet<industry_sector_parent>();
            this.transaction_type_eligibility_condition = new HashSet<transaction_type_eligibility_condition>();
            this.internal_segment_parent = new HashSet<internal_segment_parent>();
            this.internal_segment_parent1 = new HashSet<internal_segment_parent>();
            this.item_lock = new HashSet<item_lock>();
            this.link_type = new HashSet<link_type>();
            this.marketing_campaign = new HashSet<marketing_campaign>();
            this.mitigant_add_data = new HashSet<mitigant_add_data>();
            this.mitigant = new HashSet<mitigant>();
            this.participant_type = new HashSet<participant_type>();
            this.pricing_condition = new HashSet<pricing_condition>();
            this.profile = new HashSet<profile>();
            this.profile_mc = new HashSet<profile_mc>();
            this.qualitative_template = new HashSet<qualitative_template>();
            this.rating_agency = new HashSet<rating_agency>();
            this.rating = new HashSet<rating>();
            this.recovery_action_fate = new HashSet<recovery_action_fate>();
            this.recovery_type = new HashSet<recovery_type>();
            this.scoring_template_warning = new HashSet<scoring_template_warning>();
            this.screen = new HashSet<screen>();
            this.screen_mc = new HashSet<screen_mc>();
            this.security = new HashSet<security>();
            this.sms_out = new HashSet<sms_out>();
            this.software_user = new HashSet<software_user>();
            this.software_user_mc = new HashSet<software_user_mc>();
            this.specific_agreement = new HashSet<specific_agreement>();
            this.static_data_table = new HashSet<static_data_table>();
            this.status = new HashSet<status>();
            this.strategy = new HashSet<strategy>();
            this.transaction_add_data = new HashSet<transaction_add_data>();
            this.transaction_cpty = new HashSet<transaction_cpty>();
            this.transaction = new HashSet<transaction>();
            this.transaction_reallocation = new HashSet<transaction_reallocation>();
            this.transaction_type_agreement = new HashSet<transaction_type_agreement>();
            this.transaction_type = new HashSet<transaction_type>();
            this.warning_signal = new HashSet<warning_signal>();
            this.wf_sql_log = new HashSet<wf_sql_log>();
            this.working_hours_config = new HashSet<working_hours_config>();
        }
    
        public int internal_segment_id { get; set; }
        public string internal_segment_shortname { get; set; }
        public string internal_segment_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<account_type> account_type { get; set; }
        public virtual ICollection<action_type> action_type { get; set; }
        public virtual ICollection<additional_data> additional_data { get; set; }
        public virtual ICollection<aggregation_criteria> aggregation_criteria { get; set; }
        public virtual ICollection<amortization_type> amortization_type { get; set; }
        public virtual ICollection<arrangement_type> arrangement_type { get; set; }
        public virtual ICollection<asset_class> asset_class { get; set; }
        public virtual ICollection<base_rate> base_rate { get; set; }
        public virtual ICollection<collateral_type> collateral_type { get; set; }
        public virtual ICollection<combinaison_hierarchy_criteria_1> combinaison_hierarchy_criteria_1 { get; set; }
        public virtual ICollection<combinaison_hierarchy_criteria_2> combinaison_hierarchy_criteria_2 { get; set; }
        public virtual ICollection<combinaison_hierarchy_criteria_3> combinaison_hierarchy_criteria_3 { get; set; }
        public virtual ICollection<combinaison_hierarchy_criteria_4> combinaison_hierarchy_criteria_4 { get; set; }
        public virtual ICollection<commodity> commodity { get; set; }
        public virtual ICollection<constants> constants { get; set; }
        public virtual ICollection<counterparty> counterparty { get; set; }
        public virtual ICollection<counterparty_add_data> counterparty_add_data { get; set; }
        public virtual ICollection<counterparty_type> counterparty_type { get; set; }
        public virtual ICollection<country> country { get; set; }
        public virtual ICollection<country_group> country_group { get; set; }
        public virtual ICollection<credit_event_type> credit_event_type { get; set; }
        public virtual ICollection<credit_file> credit_file { get; set; }
        public virtual ICollection<credit_file_add_data> credit_file_add_data { get; set; }
        public virtual ICollection<criteria_field> criteria_field { get; set; }
        public virtual ICollection<currency> currency { get; set; }
        public virtual ICollection<decision_tree_eligibility> decision_tree_eligibility { get; set; }
        public virtual ICollection<document_category> document_category { get; set; }
        public virtual ICollection<economic_sector> economic_sector { get; set; }
        public virtual ICollection<economic_sector_parent> economic_sector_parent { get; set; }
        public virtual ICollection<eligibility_criteria> eligibility_criteria { get; set; }
        public virtual ICollection<eligibility_criteria_fields> eligibility_criteria_fields { get; set; }
        public virtual ICollection<email_out> email_out { get; set; }
        public virtual ICollection<enforcing_log> enforcing_log { get; set; }
        public virtual ICollection<estimated_probabilities> estimated_probabilities { get; set; }
        public virtual ICollection<exposure> exposure { get; set; }
        public virtual ICollection<exposure_real_time> exposure_real_time { get; set; }
        public virtual ICollection<financial_benchmark> financial_benchmark { get; set; }
        public virtual ICollection<financial_data_category> financial_data_category { get; set; }
        public virtual ICollection<financial_data_element> financial_data_element { get; set; }
        public virtual ICollection<financial_data_model> financial_data_model { get; set; }
        public virtual ICollection<financial_data_type> financial_data_type { get; set; }
        public virtual ICollection<financial_element> financial_element { get; set; }
        public virtual ICollection<financial_forecast_scenario> financial_forecast_scenario { get; set; }
        public virtual ICollection<financial_forecasting> financial_forecasting { get; set; }
        public virtual ICollection<financial_node> financial_node { get; set; }
        public virtual ICollection<financial_stress_scenario> financial_stress_scenario { get; set; }
        public virtual ICollection<financial_template> financial_template { get; set; }
        public virtual ICollection<folder_structuring> folder_structuring { get; set; }
        public virtual ICollection<group> group { get; set; }
        public virtual ICollection<group_access_right> group_access_right { get; set; }
        public virtual ICollection<group_access_right_mc> group_access_right_mc { get; set; }
        public virtual ICollection<group_mc> group_mc { get; set; }
        public virtual ICollection<holidays_config> holidays_config { get; set; }
        public virtual ICollection<industry_sector> industry_sector { get; set; }
        public virtual ICollection<industry_sector_parent> industry_sector_parent { get; set; }
        public virtual ICollection<transaction_type_eligibility_condition> transaction_type_eligibility_condition { get; set; }
        public virtual ICollection<internal_segment_parent> internal_segment_parent { get; set; }
        public virtual ICollection<internal_segment_parent> internal_segment_parent1 { get; set; }
        public virtual ICollection<item_lock> item_lock { get; set; }
        public virtual ICollection<link_type> link_type { get; set; }
        public virtual ICollection<marketing_campaign> marketing_campaign { get; set; }
        public virtual ICollection<mitigant_add_data> mitigant_add_data { get; set; }
        public virtual ICollection<mitigant> mitigant { get; set; }
        public virtual ICollection<participant_type> participant_type { get; set; }
        public virtual ICollection<pricing_condition> pricing_condition { get; set; }
        public virtual ICollection<profile> profile { get; set; }
        public virtual ICollection<profile_mc> profile_mc { get; set; }
        public virtual ICollection<qualitative_template> qualitative_template { get; set; }
        public virtual ICollection<rating_agency> rating_agency { get; set; }
        public virtual ICollection<rating> rating { get; set; }
        public virtual ICollection<recovery_action_fate> recovery_action_fate { get; set; }
        public virtual ICollection<recovery_type> recovery_type { get; set; }
        public virtual ICollection<scoring_template_warning> scoring_template_warning { get; set; }
        public virtual ICollection<screen> screen { get; set; }
        public virtual ICollection<screen_mc> screen_mc { get; set; }
        public virtual ICollection<security> security { get; set; }
        public virtual ICollection<sms_out> sms_out { get; set; }
        public virtual ICollection<software_user> software_user { get; set; }
        public virtual ICollection<software_user_mc> software_user_mc { get; set; }
        public virtual ICollection<specific_agreement> specific_agreement { get; set; }
        public virtual ICollection<static_data_table> static_data_table { get; set; }
        public virtual ICollection<status> status { get; set; }
        public virtual ICollection<strategy> strategy { get; set; }
        public virtual ICollection<transaction_add_data> transaction_add_data { get; set; }
        public virtual ICollection<transaction_cpty> transaction_cpty { get; set; }
        public virtual ICollection<transaction> transaction { get; set; }
        public virtual ICollection<transaction_reallocation> transaction_reallocation { get; set; }
        public virtual ICollection<transaction_type_agreement> transaction_type_agreement { get; set; }
        public virtual ICollection<transaction_type> transaction_type { get; set; }
        public virtual ICollection<warning_signal> warning_signal { get; set; }
        public virtual ICollection<wf_sql_log> wf_sql_log { get; set; }
        public virtual ICollection<working_hours_config> working_hours_config { get; set; }
    }
}
