//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class internal_segment_parent
    {
        public int internal_segment_id { get; set; }
        public int internal_segment_id2 { get; set; }
        public int link_type_id { get; set; }
        public Nullable<decimal> link_weight { get; set; }
        public int sequence_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual internal_segment internal_segment { get; set; }
        public virtual internal_segment internal_segment1 { get; set; }
        public virtual link_type link_type { get; set; }
    }
}
