//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_lock
    {
        public int item_lock_id { get; set; }
        public string sub_item { get; set; }
        public string status { get; set; }
        public Nullable<int> profile_id { get; set; }
        public string related_item_lock { get; set; }
        public string counterparty_related_item { get; set; }
        public string transaction_related_item { get; set; }
        public string mitigant_related_item { get; set; }
        public string credit_file_related_item { get; set; }
        public string utilization_related_item { get; set; }
        public string asset_related_item { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual profile profile { get; set; }
    }
}
