//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class link_type
    {
        public link_type()
        {
            this.counterparty_cpty = new HashSet<counterparty_cpty>();
            this.counterparty_parent = new HashSet<counterparty_parent>();
            this.country_link = new HashSet<country_link>();
            this.credit_file_transaction = new HashSet<credit_file_transaction>();
            this.economic_sector_parent = new HashSet<economic_sector_parent>();
            this.industry_sector_parent = new HashSet<industry_sector_parent>();
            this.internal_entity_parent = new HashSet<internal_entity_parent>();
            this.internal_segment_parent = new HashSet<internal_segment_parent>();
            this.strategy_criteria = new HashSet<strategy_criteria>();
            this.qualitative_template_ceiling_link_type = new HashSet<qualitative_template_ceiling_link_type>();
            this.transaction_hierarchy = new HashSet<transaction_hierarchy>();
            this.transaction_related_utilizations = new HashSet<transaction_related_utilizations>();
            this.transaction_type_hierarchy = new HashSet<transaction_type_hierarchy>();
        }
    
        public int link_type_id { get; set; }
        public string link_type_shortname { get; set; }
        public string link_type_name { get; set; }
        public string object_type { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<counterparty_cpty> counterparty_cpty { get; set; }
        public virtual ICollection<counterparty_parent> counterparty_parent { get; set; }
        public virtual ICollection<country_link> country_link { get; set; }
        public virtual ICollection<credit_file_transaction> credit_file_transaction { get; set; }
        public virtual ICollection<economic_sector_parent> economic_sector_parent { get; set; }
        public virtual ICollection<industry_sector_parent> industry_sector_parent { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual ICollection<internal_entity_parent> internal_entity_parent { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<internal_segment_parent> internal_segment_parent { get; set; }
        public virtual ICollection<strategy_criteria> strategy_criteria { get; set; }
        public virtual ICollection<qualitative_template_ceiling_link_type> qualitative_template_ceiling_link_type { get; set; }
        public virtual ICollection<transaction_hierarchy> transaction_hierarchy { get; set; }
        public virtual ICollection<transaction_related_utilizations> transaction_related_utilizations { get; set; }
        public virtual ICollection<transaction_type_hierarchy> transaction_type_hierarchy { get; set; }
    }
}
