//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class load_currency_exchange_rate
    {
        public int load_currency_exchange_rate_id { get; set; }
        public string load_currency_code { get; set; }
        public string load_exchange_date { get; set; }
        public string load_currency_rate { get; set; }
        public string error_msg { get; set; }
        public Nullable<System.DateTime> interface_date { get; set; }
        public Nullable<bool> is_interfaced { get; set; }
    }
}
