//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_deviation
    {
        public int log_deviation_id { get; set; }
        public string item { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> eligibility_condition_id { get; set; }
        public Nullable<int> eligibility_criteria_id { get; set; }
        public string eligibility_deviation_guid { get; set; }
        public string eligibility_criteria_value { get; set; }
        public string eligibility_true_value { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> deviation_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public string item_type { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> duser { get; set; }
    
        public virtual criteria_field criteria_field { get; set; }
        public virtual eligibility_condition eligibility_condition { get; set; }
        public virtual software_user software_user { get; set; }
    }
}
