//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class marketing_campaign
    {
        public marketing_campaign()
        {
            this.email_out = new HashSet<email_out>();
            this.marketing_action = new HashSet<marketing_action>();
            this.sms_out = new HashSet<sms_out>();
        }
    
        public int marketing_campaign_id { get; set; }
        public string marketing_campaign_desc { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> schedule { get; set; }
        public string email_template { get; set; }
        public string sms_template { get; set; }
        public string fax_template { get; set; }
        public string attached_document_name { get; set; }
        public string attached_document_content { get; set; }
        public byte[] attached_document { get; set; }
        public string SCPTYCategory { get; set; }
        public string SCPTYWatchList { get; set; }
        public string SCPTYRelationshipManager { get; set; }
        public string SCPTYInternalSegment { get; set; }
        public string SCPTYType { get; set; }
        public string SCPTYCountryControl { get; set; }
        public string SCPTYInternalEntity { get; set; }
        public string SCPTYCountryNationality { get; set; }
        public string SCPTYCountryResidence { get; set; }
        public string SCPTYEconomicSector { get; set; }
        public string SCPTYCountryRisk { get; set; }
        public string SCPTYStatus { get; set; }
        public string SCPTYIndustrySector { get; set; }
        public string SCPTYClassification { get; set; }
        public Nullable<bool> generated { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<email_out> email_out { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<marketing_action> marketing_action { get; set; }
        public virtual ICollection<sms_out> sms_out { get; set; }
    }
}
