//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class mitigant_valuation
    {
        public int mitigant_id { get; set; }
        public System.DateTime valuation_date { get; set; }
        public int status_id { get; set; }
        public string valuation_method { get; set; }
        public Nullable<decimal> valuation_amount { get; set; }
        public Nullable<int> valuation_ccy { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public int sequence_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<System.DateTime> next_valuation_date { get; set; }
        public string valuer { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual mitigant mitigant { get; set; }
        public virtual status status { get; set; }
    }
}
