//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class mitigant_collateral
    {
        public int collateral_type_id { get; set; }
        public int mitigant_id { get; set; }
        public int mitigant_collateral_id { get; set; }
        public string collateral_name { get; set; }
        public string collateral_description { get; set; }
        public Nullable<int> counterparty_id { get; set; }
        public string custodian { get; set; }
        public string portfolio { get; set; }
        public Nullable<int> collateral_ccy_id { get; set; }
        public Nullable<decimal> valuation { get; set; }
        public Nullable<int> valuation_ccy_id { get; set; }
        public Nullable<System.DateTime> valuation_date { get; set; }
        public string valuation_type { get; set; }
        public string valuation_source { get; set; }
        public string external_reference { get; set; }
        public Nullable<decimal> number { get; set; }
        public string collateral_adress { get; set; }
        public string registration_number { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string registration_place { get; set; }
        public string registration_organization { get; set; }
        public string insurance_policy { get; set; }
        public Nullable<System.DateTime> policy_expiry_date { get; set; }
        public string insurance_company { get; set; }
        public string policy_type { get; set; }
        public Nullable<decimal> policy_value { get; set; }
        public Nullable<int> policy_value_ccy_id { get; set; }
        public Nullable<decimal> rental_amount { get; set; }
        public Nullable<int> rental_amount_ccy_id { get; set; }
        public Nullable<decimal> charges_amount { get; set; }
        public Nullable<int> charges_amount_ccy_id { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public string sub_contractor { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> security_id { get; set; }
        public Nullable<int> commodity_id { get; set; }
    
        public virtual collateral_type collateral_type { get; set; }
        public virtual commodity commodity { get; set; }
        public virtual currency currency { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual currency currency2 { get; set; }
        public virtual currency currency3 { get; set; }
        public virtual currency currency4 { get; set; }
        public virtual mitigant mitigant { get; set; }
        public virtual security security { get; set; }
    }
}
