//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class mitigant
    {
        public mitigant()
        {
            this.credit_file_mitigant = new HashSet<credit_file_mitigant>();
            this.mitigant_action = new HashSet<mitigant_action>();
            this.mitigant_address1 = new HashSet<mitigant_address>();
            this.mitigant_collateral = new HashSet<mitigant_collateral>();
            this.mitigant_generic = new HashSet<mitigant_generic>();
            this.mitigant_participant = new HashSet<mitigant_participant>();
            this.mitigant_rating = new HashSet<mitigant_rating>();
            this.mitigant_transaction = new HashSet<mitigant_transaction>();
            this.mitigant_transaction_type = new HashSet<mitigant_transaction_type>();
            this.mitigant_valuation = new HashSet<mitigant_valuation>();
            this.transaction_recovery_mitigant = new HashSet<transaction_recovery_mitigant>();
            this.transaction_recovery = new HashSet<transaction_recovery>();
        }
    
        public int mitigant_id { get; set; }
        public string mitigant_shortname { get; set; }
        public string mitigant_name { get; set; }
        public Nullable<int> transaction_type_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string comment { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<bool> elgibility { get; set; }
        public Nullable<bool> tangibility { get; set; }
        public Nullable<bool> liquidity { get; set; }
        public string regulatory_mitigant_type { get; set; }
        public string lgd_grade { get; set; }
        public Nullable<decimal> lgd { get; set; }
        public string valuation_method { get; set; }
        public string valuation_frequency { get; set; }
        public Nullable<bool> all_beneficiary_exp { get; set; }
        public Nullable<bool> children_exp { get; set; }
        public Nullable<decimal> mitigation_percentage { get; set; }
        public Nullable<decimal> mitigation_minimum { get; set; }
        public Nullable<decimal> mitigation_maximum { get; set; }
        public Nullable<int> mitigation_ccy { get; set; }
        public string external_reference { get; set; }
        public string mitigant_screen { get; set; }
        public Nullable<int> counterparty_id { get; set; }
        public string custodian { get; set; }
        public string portfolio { get; set; }
        public Nullable<int> mitigant_ccy_id { get; set; }
        public Nullable<decimal> valuation { get; set; }
        public Nullable<int> valuation_ccy_id { get; set; }
        public Nullable<System.DateTime> valuation_date { get; set; }
        public string valuation_type { get; set; }
        public string valuation_source { get; set; }
        public Nullable<int> number { get; set; }
        public string registration_number { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string registration_place { get; set; }
        public string registration_organization { get; set; }
        public string insurance_policy { get; set; }
        public Nullable<System.DateTime> policy_expiry_date { get; set; }
        public string insurance_company { get; set; }
        public string policy_type { get; set; }
        public Nullable<decimal> policy_value { get; set; }
        public Nullable<int> policy_value_ccy_id { get; set; }
        public Nullable<decimal> rental_amount { get; set; }
        public Nullable<int> rental_amount_ccy_id { get; set; }
        public Nullable<decimal> charges_amount { get; set; }
        public Nullable<int> charges_amount_ccy_id { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public string sub_contractor { get; set; }
        public string mitigant_description { get; set; }
        public string mitigant_address { get; set; }
        public Nullable<int> collateral_type_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public string serial_number { get; set; }
        public string mitigant_state { get; set; }
        public Nullable<int> horsepower { get; set; }
        public Nullable<int> seat { get; set; }
        public Nullable<decimal> tonnage { get; set; }
        public string energy { get; set; }
        public string registration_document { get; set; }
        public string mileage { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<int> security_id { get; set; }
        public Nullable<int> commodity_id { get; set; }
        public Nullable<System.DateTime> datetime01 { get; set; }
        public Nullable<System.DateTime> datetime02 { get; set; }
        public Nullable<System.DateTime> datetime03 { get; set; }
        public Nullable<System.DateTime> datetime04 { get; set; }
        public Nullable<System.DateTime> datetime05 { get; set; }
        public Nullable<System.DateTime> datetime06 { get; set; }
        public Nullable<System.DateTime> datetime07 { get; set; }
        public Nullable<System.DateTime> datetime08 { get; set; }
        public Nullable<System.DateTime> datetime09 { get; set; }
        public Nullable<System.DateTime> datetime10 { get; set; }
        public Nullable<System.DateTime> datetime11 { get; set; }
        public Nullable<System.DateTime> datetime12 { get; set; }
        public Nullable<System.DateTime> datetime13 { get; set; }
        public Nullable<System.DateTime> datetime14 { get; set; }
        public Nullable<System.DateTime> datetime15 { get; set; }
    
        public virtual collateral_type collateral_type { get; set; }
        public virtual commodity commodity { get; set; }
        public virtual ICollection<credit_file_mitigant> credit_file_mitigant { get; set; }
        public virtual currency currency { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual currency currency2 { get; set; }
        public virtual currency currency3 { get; set; }
        public virtual currency currency4 { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<mitigant_action> mitigant_action { get; set; }
        public virtual ICollection<mitigant_address> mitigant_address1 { get; set; }
        public virtual ICollection<mitigant_collateral> mitigant_collateral { get; set; }
        public virtual mitigant_comment mitigant_comment { get; set; }
        public virtual ICollection<mitigant_generic> mitigant_generic { get; set; }
        public virtual ICollection<mitigant_participant> mitigant_participant { get; set; }
        public virtual ICollection<mitigant_rating> mitigant_rating { get; set; }
        public virtual security security { get; set; }
        public virtual status status { get; set; }
        public virtual ICollection<mitigant_transaction> mitigant_transaction { get; set; }
        public virtual transaction_type transaction_type { get; set; }
        public virtual ICollection<mitigant_transaction_type> mitigant_transaction_type { get; set; }
        public virtual ICollection<mitigant_valuation> mitigant_valuation { get; set; }
        public virtual ICollection<transaction_recovery_mitigant> transaction_recovery_mitigant { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery { get; set; }
    }
}
