//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class outstanding
    {
        public int outstanding_id { get; set; }
        public System.DateTime outstanding_date { get; set; }
        public int counterparty_id { get; set; }
        public Nullable<int> transaction_type_id { get; set; }
        public string reference { get; set; }
        public Nullable<int> utilization_number { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<decimal> approved_amount { get; set; }
        public Nullable<int> approved_amout_ccy_id { get; set; }
        public Nullable<System.DateTime> activation_date { get; set; }
        public Nullable<decimal> activated_amount { get; set; }
        public Nullable<int> activated_amout_ccy_id { get; set; }
        public Nullable<int> remaining_term_number { get; set; }
        public Nullable<System.DateTime> last_term_date { get; set; }
        public Nullable<decimal> notional_outstanding_amount { get; set; }
        public Nullable<int> notional_outstanding_amount_ccy_id { get; set; }
        public Nullable<decimal> interest_outstanding_amount { get; set; }
        public Nullable<int> interest_outstanding_amount_ccy_id { get; set; }
        public Nullable<decimal> average_term_amount { get; set; }
        public Nullable<int> average_term_amount_ccy_id { get; set; }
        public Nullable<bool> is_anticipated { get; set; }
        public Nullable<int> interfaced { get; set; }
        public string comment { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<System.DateTime> first_term_date { get; set; }
        public Nullable<decimal> spread { get; set; }
        public Nullable<decimal> Tenor { get; set; }
        public Nullable<decimal> unpaid_tenor { get; set; }
        public string account_number { get; set; }
        public Nullable<int> transaction_id { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual currency currency { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual currency currency2 { get; set; }
        public virtual currency currency3 { get; set; }
        public virtual currency currency4 { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
