//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class participant_type
    {
        public participant_type()
        {
            this.mitigant_participant = new HashSet<mitigant_participant>();
        }
    
        public int participant_type_id { get; set; }
        public string participant_type_shortname { get; set; }
        public string participant_type_name { get; set; }
        public string participant_type_category { get; set; }
        public Nullable<int> transaction_type_id { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<mitigant_participant> mitigant_participant { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
