//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public payment()
        {
            this.payment_posting = new HashSet<payment_posting>();
        }
    
        public int payment_id { get; set; }
        public string payment_shortname { get; set; }
        public Nullable<int> counterparty_id { get; set; }
        public string payment_reference { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string external_reference { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public Nullable<int> payment_amount_ccy_id { get; set; }
        public Nullable<decimal> posted_amount { get; set; }
        public Nullable<int> posted_amount_ccy_id { get; set; }
        public Nullable<decimal> posting_outstanding_amount { get; set; }
        public Nullable<int> posting_outstanding_amount_ccy_id { get; set; }
        public string payment_method { get; set; }
        public string comment { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual currency currency { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual currency currency2 { get; set; }
        public virtual ICollection<payment_posting> payment_posting { get; set; }
    }
}
