//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricing_condition_fees
    {
        public int pricing_condition_fees_id { get; set; }
        public Nullable<int> pricing_condition_id { get; set; }
        public string fees_type { get; set; }
        public Nullable<decimal> fees_amount { get; set; }
        public Nullable<int> fees_amount_ccy_id { get; set; }
        public Nullable<decimal> fees_rate { get; set; }
        public string fees_payment_frequency { get; set; }
        public Nullable<decimal> fees_vat { get; set; }
        public Nullable<System.DateTime> period_from { get; set; }
        public Nullable<System.DateTime> period_to { get; set; }
        public string fees_base_amount { get; set; }
        public string fees_effect { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual pricing_condition pricing_condition { get; set; }
    }
}
