//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricing_condition
    {
        public pricing_condition()
        {
            this.eligibility_condition = new HashSet<eligibility_condition>();
            this.pricing_condition_fees = new HashSet<pricing_condition_fees>();
            this.transaction_type_agreement = new HashSet<transaction_type_agreement>();
        }
    
        public int pricing_condition_id { get; set; }
        public string pricing_condition_shortname { get; set; }
        public string pricing_condition_name { get; set; }
        public Nullable<int> base_rate_id { get; set; }
        public Nullable<decimal> spread { get; set; }
        public Nullable<decimal> fixe { get; set; }
        public string coupon_frequency { get; set; }
        public string accural_basis { get; set; }
        public Nullable<int> amortization_type_id { get; set; }
        public string amortization_frequency { get; set; }
        public string capitalization_interest_method { get; set; }
        public Nullable<int> grace_period { get; set; }
        public Nullable<decimal> anticipated_spread { get; set; }
        public Nullable<decimal> anticipated_fixed_rate { get; set; }
        public Nullable<decimal> amount_min { get; set; }
        public Nullable<decimal> amount_max { get; set; }
        public Nullable<decimal> duration_min { get; set; }
        public Nullable<decimal> duration_max { get; set; }
        public Nullable<decimal> rate_min { get; set; }
        public Nullable<decimal> rate_max { get; set; }
        public Nullable<decimal> dbr { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> tenor { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<int> commission_ccy_id { get; set; }
    
        public virtual amortization_type amortization_type { get; set; }
        public virtual base_rate base_rate { get; set; }
        public virtual currency currency { get; set; }
        public virtual ICollection<eligibility_condition> eligibility_condition { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<pricing_condition_fees> pricing_condition_fees { get; set; }
        public virtual ICollection<transaction_type_agreement> transaction_type_agreement { get; set; }
    }
}
