//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public profile()
        {
            this.additional_data_profiles = new HashSet<additional_data_profiles>();
            this.fields_access_right = new HashSet<fields_access_right>();
            this.fields_access_right_mc = new HashSet<fields_access_right_mc>();
            this.item_lock = new HashSet<item_lock>();
            this.profile_access_right_mc = new HashSet<profile_access_right_mc>();
            this.profile_access_right = new HashSet<profile_access_right>();
            this.profile_access_right1 = new HashSet<profile_access_right>();
            this.profile_access_right_mc1 = new HashSet<profile_access_right_mc>();
            this.profile_workflow_right = new HashSet<profile_workflow_right>();
            this.user_profile_mc = new HashSet<user_profile_mc>();
            this.user_profile = new HashSet<user_profile>();
        }
    
        public int profile_id { get; set; }
        public string profile_shortname { get; set; }
        public string profile_name { get; set; }
        public string home_profile_config { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<bool> stop_wf { get; set; }
    
        public virtual ICollection<additional_data_profiles> additional_data_profiles { get; set; }
        public virtual ICollection<fields_access_right> fields_access_right { get; set; }
        public virtual ICollection<fields_access_right_mc> fields_access_right_mc { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<item_lock> item_lock { get; set; }
        public virtual ICollection<profile_access_right_mc> profile_access_right_mc { get; set; }
        public virtual ICollection<profile_access_right> profile_access_right { get; set; }
        public virtual ICollection<profile_access_right> profile_access_right1 { get; set; }
        public virtual ICollection<profile_access_right_mc> profile_access_right_mc1 { get; set; }
        public virtual ICollection<profile_workflow_right> profile_workflow_right { get; set; }
        public virtual ICollection<user_profile_mc> user_profile_mc { get; set; }
        public virtual ICollection<user_profile> user_profile { get; set; }
    }
}
