//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualitative_template
    {
        public qualitative_template()
        {
            this.qualitative_structure = new HashSet<qualitative_structure>();
            this.qualitative_template_ceiling_link_type = new HashSet<qualitative_template_ceiling_link_type>();
            this.rating_qualitative_template = new HashSet<rating_qualitative_template>();
        }
    
        public int qualitative_template_id { get; set; }
        public int qualitative_template_version { get; set; }
        public string qualitative_template_shortname { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<bool> ceiling { get; set; }
        public string condition { get; set; }
        public int sequence_id { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<bool> enable_adjustment { get; set; }
    
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<qualitative_structure> qualitative_structure { get; set; }
        public virtual ICollection<qualitative_template_ceiling_link_type> qualitative_template_ceiling_link_type { get; set; }
        public virtual ICollection<rating_qualitative_template> rating_qualitative_template { get; set; }
    }
}
