//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualitative_element
    {
        public qualitative_element()
        {
            this.qualitative_element_answer = new HashSet<qualitative_element_answer>();
            this.qualitative_structure = new HashSet<qualitative_structure>();
        }
    
        public int qualitative_element_id { get; set; }
        public string qualitative_element_shortname { get; set; }
        public string qualitative_element_name { get; set; }
        public string qualitative_element_description { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<qualitative_element_answer> qualitative_element_answer { get; set; }
        public virtual ICollection<qualitative_structure> qualitative_structure { get; set; }
    }
}
