//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualitative_answer
    {
        public qualitative_answer()
        {
            this.counterparty_qualitative_element = new HashSet<counterparty_qualitative_element>();
            this.qualitative_element_answer = new HashSet<qualitative_element_answer>();
        }
    
        public int qualitative_answer_id { get; set; }
        public string qualitative_answer_name { get; set; }
        public string qualitative_answer_description { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<counterparty_qualitative_element> counterparty_qualitative_element { get; set; }
        public virtual ICollection<qualitative_element_answer> qualitative_element_answer { get; set; }
    }
}
