//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualitative_structure
    {
        public qualitative_structure()
        {
            this.counterparty_qualitative_element = new HashSet<counterparty_qualitative_element>();
            this.counterparty_qualitative_node = new HashSet<counterparty_qualitative_node>();
        }
    
        public int qualitative_structure_id { get; set; }
        public Nullable<int> qualitative_template_id { get; set; }
        public Nullable<int> qualitative_template_version { get; set; }
        public Nullable<int> qualitative_node_id { get; set; }
        public Nullable<int> qualitative_element_id { get; set; }
        public Nullable<int> qualitative_parent_node_id { get; set; }
        public Nullable<bool> adjustment { get; set; }
        public Nullable<decimal> max_positive_adjustment { get; set; }
        public Nullable<decimal> max_negative_adjustment { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<counterparty_qualitative_element> counterparty_qualitative_element { get; set; }
        public virtual ICollection<counterparty_qualitative_node> counterparty_qualitative_node { get; set; }
        public virtual qualitative_element qualitative_element { get; set; }
        public virtual qualitative_node qualitative_node { get; set; }
        public virtual qualitative_node qualitative_node1 { get; set; }
        public virtual qualitative_template qualitative_template { get; set; }
    }
}
