//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public rating()
        {
            this.bkp_estimated_probability = new HashSet<bkp_estimated_probability>();
            this.bkp_transaction_rating_el = new HashSet<bkp_transaction_rating_el>();
            this.bkt_cure_probability_history = new HashSet<bkt_cure_probability_history>();
            this.bkt_discriminatory_history = new HashSet<bkt_discriminatory_history>();
            this.bkt_discriminatory_history_detail = new HashSet<bkt_discriminatory_history_detail>();
            this.bkt_discriminatory_history_detail1 = new HashSet<bkt_discriminatory_history_detail>();
            this.bkt_pd_history = new HashSet<bkt_pd_history>();
            this.bkt_pd_history_detail = new HashSet<bkt_pd_history_detail>();
            this.bkt_pd_history_detail1 = new HashSet<bkt_pd_history_detail>();
            this.bkt_rest_probability_history = new HashSet<bkt_rest_probability_history>();
            this.counterparty_external_rating = new HashSet<counterparty_external_rating>();
            this.counterparty_internal_rating = new HashSet<counterparty_internal_rating>();
            this.credit_file_rating = new HashSet<credit_file_rating>();
            this.estimated_probabilities = new HashSet<estimated_probabilities>();
            this.estimated_probabilities_his = new HashSet<estimated_probabilities_his>();
            this.estimated_probability = new HashSet<estimated_probability>();
            this.mitigant_rating = new HashSet<mitigant_rating>();
            this.rating_qualitative_template = new HashSet<rating_qualitative_template>();
            this.transaction_limit_monitoring = new HashSet<transaction_limit_monitoring>();
            this.transaction_limit_monitoring1 = new HashSet<transaction_limit_monitoring>();
            this.transaction_rating_el = new HashSet<transaction_rating_el>();
            this.transaction_rating = new HashSet<transaction_rating>();
            this.transition_matrix = new HashSet<transition_matrix>();
            this.transition_matrix1 = new HashSet<transition_matrix>();
        }
    
        public int rating_id { get; set; }
        public int rating_type_id { get; set; }
        public string rating_value { get; set; }
        public Nullable<decimal> rating_rank { get; set; }
        public string rating_class { get; set; }
        public Nullable<decimal> maximum_score { get; set; }
        public Nullable<decimal> pd { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string rating_description { get; set; }
        public string rating_scale { get; set; }
        public Nullable<decimal> lgd { get; set; }
        public Nullable<decimal> el { get; set; }
        public Nullable<decimal> capital_charge { get; set; }
        public Nullable<decimal> external_rating { get; set; }
    
        public virtual ICollection<bkp_estimated_probability> bkp_estimated_probability { get; set; }
        public virtual ICollection<bkp_transaction_rating_el> bkp_transaction_rating_el { get; set; }
        public virtual ICollection<bkt_cure_probability_history> bkt_cure_probability_history { get; set; }
        public virtual ICollection<bkt_discriminatory_history> bkt_discriminatory_history { get; set; }
        public virtual ICollection<bkt_discriminatory_history_detail> bkt_discriminatory_history_detail { get; set; }
        public virtual ICollection<bkt_discriminatory_history_detail> bkt_discriminatory_history_detail1 { get; set; }
        public virtual ICollection<bkt_pd_history> bkt_pd_history { get; set; }
        public virtual ICollection<bkt_pd_history_detail> bkt_pd_history_detail { get; set; }
        public virtual ICollection<bkt_pd_history_detail> bkt_pd_history_detail1 { get; set; }
        public virtual ICollection<bkt_rest_probability_history> bkt_rest_probability_history { get; set; }
        public virtual ICollection<counterparty_external_rating> counterparty_external_rating { get; set; }
        public virtual ICollection<counterparty_internal_rating> counterparty_internal_rating { get; set; }
        public virtual ICollection<credit_file_rating> credit_file_rating { get; set; }
        public virtual ICollection<estimated_probabilities> estimated_probabilities { get; set; }
        public virtual ICollection<estimated_probabilities_his> estimated_probabilities_his { get; set; }
        public virtual ICollection<estimated_probability> estimated_probability { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<mitigant_rating> mitigant_rating { get; set; }
        public virtual ICollection<rating_qualitative_template> rating_qualitative_template { get; set; }
        public virtual rating_type rating_type { get; set; }
        public virtual ICollection<transaction_limit_monitoring> transaction_limit_monitoring { get; set; }
        public virtual ICollection<transaction_limit_monitoring> transaction_limit_monitoring1 { get; set; }
        public virtual ICollection<transaction_rating_el> transaction_rating_el { get; set; }
        public virtual ICollection<transaction_rating> transaction_rating { get; set; }
        public virtual ICollection<transition_matrix> transition_matrix { get; set; }
        public virtual ICollection<transition_matrix> transition_matrix1 { get; set; }
    }
}
