//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class recovery_arrangement_action
    {
        public int recovery_arrangement_action_id { get; set; }
        public Nullable<int> transaction_recovery_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> arrangement_type_id { get; set; }
        public Nullable<System.DateTime> recovery_arrangement_action_date { get; set; }
        public string recovery_arrangement_action_description { get; set; }
        public string recovery_arrangement_action_shortname { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string payment_method { get; set; }
        public Nullable<int> amount_ccy { get; set; }
    
        public virtual arrangement_type arrangement_type { get; set; }
        public virtual currency currency { get; set; }
        public virtual software_user software_user { get; set; }
        public virtual status status { get; set; }
        public virtual transaction_recovery transaction_recovery { get; set; }
    }
}
