//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class scoring_template
    {
        public scoring_template()
        {
            this.counterparty = new HashSet<counterparty>();
            this.financial_analysis_session = new HashSet<financial_analysis_session>();
            this.financial_forecasting = new HashSet<financial_forecasting>();
            this.scoring_session = new HashSet<scoring_session>();
            this.scoring_template_warning = new HashSet<scoring_template_warning>();
        }
    
        public int scoring_template_id { get; set; }
        public string scoring_template_shortname { get; set; }
        public string scoring_template_description { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<int> financial_template_id { get; set; }
        public Nullable<int> qualitative_template_id { get; set; }
        public Nullable<decimal> qualitative_weight { get; set; }
        public Nullable<decimal> financial_weight { get; set; }
        public string item_type { get; set; }
        public string condition { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> rating_type_id { get; set; }
    
        public virtual ICollection<counterparty> counterparty { get; set; }
        public virtual ICollection<financial_analysis_session> financial_analysis_session { get; set; }
        public virtual ICollection<financial_forecasting> financial_forecasting { get; set; }
        public virtual rating_type rating_type { get; set; }
        public virtual ICollection<scoring_session> scoring_session { get; set; }
        public virtual ICollection<scoring_template_warning> scoring_template_warning { get; set; }
    }
}
