//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class scoring_session
    {
        public scoring_session()
        {
            this.counterparty_financial_structure = new HashSet<counterparty_financial_structure>();
            this.counterparty_internal_rating = new HashSet<counterparty_internal_rating>();
            this.counterparty_qualitative_element = new HashSet<counterparty_qualitative_element>();
            this.counterparty_qualitative_node = new HashSet<counterparty_qualitative_node>();
        }
    
        public int scoring_session_id { get; set; }
        public int status_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public string item { get; set; }
        public Nullable<System.DateTime> scoring_date { get; set; }
        public Nullable<int> scoring_template_id { get; set; }
        public Nullable<int> qualitative_template_version { get; set; }
        public Nullable<int> financial_template_version { get; set; }
        public Nullable<decimal> qualitative_score { get; set; }
        public Nullable<decimal> financial_score { get; set; }
        public Nullable<decimal> adjusted_qualitative_score { get; set; }
        public Nullable<decimal> adjusted_financial_score { get; set; }
        public string comment { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<System.DateTime> rating_target_date { get; set; }
    
        public virtual ICollection<counterparty_financial_structure> counterparty_financial_structure { get; set; }
        public virtual ICollection<counterparty_internal_rating> counterparty_internal_rating { get; set; }
        public virtual ICollection<counterparty_qualitative_element> counterparty_qualitative_element { get; set; }
        public virtual ICollection<counterparty_qualitative_node> counterparty_qualitative_node { get; set; }
        public virtual scoring_template scoring_template { get; set; }
        public virtual status status { get; set; }
    }
}
