//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class screen
    {
        public screen()
        {
            this.fields_access_right = new HashSet<fields_access_right>();
            this.fields_access_right_mc = new HashSet<fields_access_right_mc>();
            this.profile_access_right = new HashSet<profile_access_right>();
            this.profile_access_right1 = new HashSet<profile_access_right>();
            this.profile_access_right_mc = new HashSet<profile_access_right_mc>();
            this.profile_access_right_mc1 = new HashSet<profile_access_right_mc>();
        }
    
        public int screen_id { get; set; }
        public string screen_tab { get; set; }
        public string screen_shortname { get; set; }
        public string display { get; set; }
        public bool visible { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<fields_access_right> fields_access_right { get; set; }
        public virtual ICollection<fields_access_right_mc> fields_access_right_mc { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<profile_access_right> profile_access_right { get; set; }
        public virtual ICollection<profile_access_right> profile_access_right1 { get; set; }
        public virtual ICollection<profile_access_right_mc> profile_access_right_mc { get; set; }
        public virtual ICollection<profile_access_right_mc> profile_access_right_mc1 { get; set; }
    }
}
