//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class software_user
    {
        public software_user()
        {
            this.collect_question = new HashSet<collect_question>();
            this.counterparty = new HashSet<counterparty>();
            this.counterparty1 = new HashSet<counterparty>();
            this.counterparty2 = new HashSet<counterparty>();
            this.counterparty_account = new HashSet<counterparty_account>();
            this.counterparty_internal_rating = new HashSet<counterparty_internal_rating>();
            this.counterparty_user = new HashSet<counterparty_user>();
            this.credit_file = new HashSet<credit_file>();
            this.credit_file1 = new HashSet<credit_file>();
            this.credit_file2 = new HashSet<credit_file>();
            this.credit_file3 = new HashSet<credit_file>();
            this.credit_file_condition = new HashSet<credit_file_condition>();
            this.credit_file_user = new HashSet<credit_file_user>();
            this.enforcing_log = new HashSet<enforcing_log>();
            this.log_deviation = new HashSet<log_deviation>();
            this.recovery_arrangement_action = new HashSet<recovery_arrangement_action>();
            this.software_user_target = new HashSet<software_user_target>();
            this.stopwf_log = new HashSet<stopwf_log>();
            this.transaction_condition = new HashSet<transaction_condition>();
            this.transaction_recovery = new HashSet<transaction_recovery>();
            this.transaction = new HashSet<transaction>();
            this.transaction1 = new HashSet<transaction>();
            this.transaction_user = new HashSet<transaction_user>();
            this.user_activity = new HashSet<user_activity>();
            this.user_group_mc = new HashSet<user_group_mc>();
            this.user_group = new HashSet<user_group>();
            this.user_profile_mc = new HashSet<user_profile_mc>();
            this.user_profile = new HashSet<user_profile>();
            this.wf_task_dispatch = new HashSet<wf_task_dispatch>();
        }
    
        public int user_id { get; set; }
        public string user_shortname { get; set; }
        public string user_name { get; set; }
        public string position { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string password { get; set; }
        public string home_user_config { get; set; }
        public string culture_language { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string external_ref1 { get; set; }
        public byte[] digital_signature { get; set; }
        public Nullable<bool> mobile_access { get; set; }
    
        public virtual ICollection<collect_question> collect_question { get; set; }
        public virtual ICollection<counterparty> counterparty { get; set; }
        public virtual ICollection<counterparty> counterparty1 { get; set; }
        public virtual ICollection<counterparty> counterparty2 { get; set; }
        public virtual ICollection<counterparty_account> counterparty_account { get; set; }
        public virtual ICollection<counterparty_internal_rating> counterparty_internal_rating { get; set; }
        public virtual ICollection<counterparty_user> counterparty_user { get; set; }
        public virtual ICollection<credit_file> credit_file { get; set; }
        public virtual ICollection<credit_file> credit_file1 { get; set; }
        public virtual ICollection<credit_file> credit_file2 { get; set; }
        public virtual ICollection<credit_file> credit_file3 { get; set; }
        public virtual ICollection<credit_file_condition> credit_file_condition { get; set; }
        public virtual ICollection<credit_file_user> credit_file_user { get; set; }
        public virtual ICollection<enforcing_log> enforcing_log { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<log_deviation> log_deviation { get; set; }
        public virtual ICollection<recovery_arrangement_action> recovery_arrangement_action { get; set; }
        public virtual ICollection<software_user_target> software_user_target { get; set; }
        public virtual ICollection<stopwf_log> stopwf_log { get; set; }
        public virtual ICollection<transaction_condition> transaction_condition { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery { get; set; }
        public virtual ICollection<transaction> transaction { get; set; }
        public virtual ICollection<transaction> transaction1 { get; set; }
        public virtual ICollection<transaction_user> transaction_user { get; set; }
        public virtual ICollection<user_activity> user_activity { get; set; }
        public virtual ICollection<user_group_mc> user_group_mc { get; set; }
        public virtual ICollection<user_group> user_group { get; set; }
        public virtual ICollection<user_profile_mc> user_profile_mc { get; set; }
        public virtual ICollection<user_profile> user_profile { get; set; }
        public virtual ICollection<wf_task_dispatch> wf_task_dispatch { get; set; }
    }
}
