//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class software_user_target
    {
        public int software_user_target_id { get; set; }
        public Nullable<decimal> software_user_target_amount { get; set; }
        public string software_user_target_currency { get; set; }
        public string software_user_target_period { get; set; }
        public int software_user_target_user_id { get; set; }
        public Nullable<int> software_user_target_counterparty_type_id { get; set; }
        public Nullable<int> software_user_target_asset_class_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual asset_class asset_class { get; set; }
        public virtual counterparty_type counterparty_type { get; set; }
        public virtual software_user software_user { get; set; }
    }
}
