//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class specific_agreement
    {
        public specific_agreement()
        {
            this.transaction = new HashSet<transaction>();
            this.transaction_type_agreement = new HashSet<transaction_type_agreement>();
            this.transaction_type = new HashSet<transaction_type>();
        }
    
        public int specific_agreement_id { get; set; }
        public string specific_agreement_shortname { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string specific_agreement_name { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> amount_ccy { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<transaction> transaction { get; set; }
        public virtual ICollection<transaction_type_agreement> transaction_type_agreement { get; set; }
        public virtual ICollection<transaction_type> transaction_type { get; set; }
    }
}
