//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.accounting_output = new HashSet<accounting_output>();
            this.bkt_pd_history_detail = new HashSet<bkt_pd_history_detail>();
            this.counterparty = new HashSet<counterparty>();
            this.counterparty1 = new HashSet<counterparty>();
            this.counterparty_credit_state_history = new HashSet<counterparty_credit_state_history>();
            this.counterparty_internal_rating = new HashSet<counterparty_internal_rating>();
            this.counterparty_internal_rating1 = new HashSet<counterparty_internal_rating>();
            this.credit_file = new HashSet<credit_file>();
            this.credit_file_condition = new HashSet<credit_file_condition>();
            this.credit_file_covenant = new HashSet<credit_file_covenant>();
            this.credit_file_mitigant = new HashSet<credit_file_mitigant>();
            this.credit_file_opinion = new HashSet<credit_file_opinion>();
            this.credit_file_rating = new HashSet<credit_file_rating>();
            this.financial_analysis_session = new HashSet<financial_analysis_session>();
            this.limit = new HashSet<limit>();
            this.limit_monitoring_mitigant = new HashSet<limit_monitoring_mitigant>();
            this.mitigant = new HashSet<mitigant>();
            this.mitigant_transaction = new HashSet<mitigant_transaction>();
            this.mitigant_valuation = new HashSet<mitigant_valuation>();
            this.recovery_arrangement_action = new HashSet<recovery_arrangement_action>();
            this.scoring_session = new HashSet<scoring_session>();
            this.transaction = new HashSet<transaction>();
            this.transaction_amount = new HashSet<transaction_amount>();
            this.transaction_condition = new HashSet<transaction_condition>();
            this.transaction_condition_tier = new HashSet<transaction_condition_tier>();
            this.transaction_covenant_history = new HashSet<transaction_covenant_history>();
            this.transaction_covenant = new HashSet<transaction_covenant>();
            this.transaction_credit_event = new HashSet<transaction_credit_event>();
            this.transaction_excess = new HashSet<transaction_excess>();
            this.transaction_limit_monitoring = new HashSet<transaction_limit_monitoring>();
            this.transaction_overtaken = new HashSet<transaction_overtaken>();
            this.transaction_rating = new HashSet<transaction_rating>();
            this.transaction_reallocation = new HashSet<transaction_reallocation>();
            this.transaction_recovery = new HashSet<transaction_recovery>();
            this.transaction_recovery1 = new HashSet<transaction_recovery>();
            this.transaction_related_utilizations = new HashSet<transaction_related_utilizations>();
            this.transaction1 = new HashSet<transaction>();
        }
    
        public int status_id { get; set; }
        public string status_shortname { get; set; }
        public string status_name { get; set; }
        public Nullable<int> internal_entity_id { get; set; }
        public Nullable<int> internal_segment_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<accounting_output> accounting_output { get; set; }
        public virtual ICollection<bkt_pd_history_detail> bkt_pd_history_detail { get; set; }
        public virtual ICollection<counterparty> counterparty { get; set; }
        public virtual ICollection<counterparty> counterparty1 { get; set; }
        public virtual ICollection<counterparty_credit_state_history> counterparty_credit_state_history { get; set; }
        public virtual ICollection<counterparty_internal_rating> counterparty_internal_rating { get; set; }
        public virtual ICollection<counterparty_internal_rating> counterparty_internal_rating1 { get; set; }
        public virtual ICollection<credit_file> credit_file { get; set; }
        public virtual ICollection<credit_file_condition> credit_file_condition { get; set; }
        public virtual ICollection<credit_file_covenant> credit_file_covenant { get; set; }
        public virtual ICollection<credit_file_mitigant> credit_file_mitigant { get; set; }
        public virtual ICollection<credit_file_opinion> credit_file_opinion { get; set; }
        public virtual ICollection<credit_file_rating> credit_file_rating { get; set; }
        public virtual ICollection<financial_analysis_session> financial_analysis_session { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual ICollection<limit> limit { get; set; }
        public virtual ICollection<limit_monitoring_mitigant> limit_monitoring_mitigant { get; set; }
        public virtual ICollection<mitigant> mitigant { get; set; }
        public virtual ICollection<mitigant_transaction> mitigant_transaction { get; set; }
        public virtual ICollection<mitigant_valuation> mitigant_valuation { get; set; }
        public virtual ICollection<recovery_arrangement_action> recovery_arrangement_action { get; set; }
        public virtual ICollection<scoring_session> scoring_session { get; set; }
        public virtual ICollection<transaction> transaction { get; set; }
        public virtual ICollection<transaction_amount> transaction_amount { get; set; }
        public virtual ICollection<transaction_condition> transaction_condition { get; set; }
        public virtual ICollection<transaction_condition_tier> transaction_condition_tier { get; set; }
        public virtual ICollection<transaction_covenant_history> transaction_covenant_history { get; set; }
        public virtual ICollection<transaction_covenant> transaction_covenant { get; set; }
        public virtual ICollection<transaction_credit_event> transaction_credit_event { get; set; }
        public virtual ICollection<transaction_excess> transaction_excess { get; set; }
        public virtual ICollection<transaction_limit_monitoring> transaction_limit_monitoring { get; set; }
        public virtual ICollection<transaction_overtaken> transaction_overtaken { get; set; }
        public virtual ICollection<transaction_rating> transaction_rating { get; set; }
        public virtual ICollection<transaction_reallocation> transaction_reallocation { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery { get; set; }
        public virtual ICollection<transaction_recovery> transaction_recovery1 { get; set; }
        public virtual ICollection<transaction_related_utilizations> transaction_related_utilizations { get; set; }
        public virtual ICollection<transaction> transaction1 { get; set; }
    }
}
