//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class stopwf_log
    {
        public int stopwf_log_id { get; set; }
        public string wf_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual software_user software_user { get; set; }
    }
}
