//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class strategy_criteria
    {
        public int strategy_id { get; set; }
        public int criteria_rank { get; set; }
        public string criteria_shortname { get; set; }
        public string criteria_aggregation_level { get; set; }
        public Nullable<int> criteria_aggregation_value { get; set; }
        public string criteria_content_query { get; set; }
        public int sequence_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> link_type_id { get; set; }
    
        public virtual link_type link_type { get; set; }
        public virtual strategy strategy { get; set; }
    }
}
