//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class strategy_exposure
    {
        public strategy_exposure()
        {
            this.exposure = new HashSet<exposure>();
            this.exposure_real_time = new HashSet<exposure_real_time>();
            this.impact_generation = new HashSet<impact_generation>();
            this.impact_generation_real_time = new HashSet<impact_generation_real_time>();
            this.limit = new HashSet<limit>();
        }
    
        public int exposure_id { get; set; }
        public int strategy_id { get; set; }
        public string exposure_shortname { get; set; }
        public string exposure_calc_formula { get; set; }
        public string limit_type { get; set; }
        public Nullable<decimal> default_limit { get; set; }
        public string limit_calc_formula { get; set; }
        public string limit_calc_factor { get; set; }
        public Nullable<decimal> exposure_warning_limit { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual ICollection<exposure> exposure { get; set; }
        public virtual ICollection<exposure_real_time> exposure_real_time { get; set; }
        public virtual ICollection<impact_generation> impact_generation { get; set; }
        public virtual ICollection<impact_generation_real_time> impact_generation_real_time { get; set; }
        public virtual ICollection<limit> limit { get; set; }
        public virtual strategy strategy { get; set; }
    }
}
