//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_overtaken
    {
        public int transaction_overtaken_id { get; set; }
        public string transaction_overtaken_shortname { get; set; }
        public string overtaken_description { get; set; }
        public int transaction_id { get; set; }
        public int transaction_type_id { get; set; }
        public int status_id { get; set; }
        public Nullable<System.DateTime> overtaken_application_date { get; set; }
        public Nullable<decimal> overtaken_amount { get; set; }
        public Nullable<int> overtaken_amount_currency_id { get; set; }
        public Nullable<System.DateTime> overtaken_expiry_date { get; set; }
        public Nullable<System.DateTime> overtaken_approval_date { get; set; }
        public string mitigant_description { get; set; }
        public string comment_1 { get; set; }
        public string comment_2 { get; set; }
        public string comment_3 { get; set; }
        public string comment_4 { get; set; }
        public string comment_5 { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual status status { get; set; }
        public virtual transaction transaction { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
