//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_rating
    {
        public int transaction_rating_id { get; set; }
        public int transaction_id { get; set; }
        public int rating_id { get; set; }
        public System.DateTime rating_date { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual rating rating { get; set; }
        public virtual status status { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
