//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_type_fees
    {
        public int transaction_type_id { get; set; }
        public string fees_type { get; set; }
        public Nullable<decimal> fees_amount { get; set; }
        public Nullable<int> fees_amount_ccy_id { get; set; }
        public Nullable<decimal> fees_rate { get; set; }
        public string fees_payment_frequency { get; set; }
        public Nullable<decimal> fees_vat { get; set; }
        public string fees_effect { get; set; }
        public Nullable<decimal> max_amount { get; set; }
        public int sequence_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<decimal> fee_max_rate { get; set; }
        public Nullable<decimal> fee_min_rate { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
