//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_amount_fees
    {
        public int transaction_amount_fees_id { get; set; }
        public string fees_type { get; set; }
        public Nullable<decimal> fees_amount { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<int> amount_ccy_id { get; set; }
        public int transaction_amount_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> fees_type_id { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual transaction_amount transaction_amount { get; set; }
    }
}
