//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_limit_monitoring
    {
        public int transaction_type_id { get; set; }
        public int status_id { get; set; }
        public int rating_from_id { get; set; }
        public int rating_to_id { get; set; }
        public Nullable<decimal> variation_percent { get; set; }
        public Nullable<decimal> transaction_amount { get; set; }
        public Nullable<int> amount_ccy_id { get; set; }
        public int transaction_limit_monitoring_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual rating rating { get; set; }
        public virtual rating rating1 { get; set; }
        public virtual status status { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
