//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_related_utilizations
    {
        public int transaction_related_utilizations_id { get; set; }
        public Nullable<decimal> transaction_related_utilizations_amount { get; set; }
        public Nullable<int> transaction_related_utilizations_ccy_id { get; set; }
        public Nullable<System.DateTime> transaction_related_utilizations_date { get; set; }
        public int transaction_type_id { get; set; }
        public int transaction_id { get; set; }
        public int status_id { get; set; }
        public int link_type_id { get; set; }
        public string beneficiary { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string loan_account_number { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual link_type link_type { get; set; }
        public virtual status status { get; set; }
        public virtual transaction transaction { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
