//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_recovery
    {
        public transaction_recovery()
        {
            this.counterparty_add_data_litigation = new HashSet<counterparty_add_data_litigation>();
            this.recovery_arrangement_action = new HashSet<recovery_arrangement_action>();
            this.recovery_credit_event = new HashSet<recovery_credit_event>();
            this.transaction_recovery_mitigant = new HashSet<transaction_recovery_mitigant>();
        }
    
        public int transaction_recovery_id { get; set; }
        public string recovery_shortname { get; set; }
        public Nullable<int> recovery_type_id { get; set; }
        public Nullable<System.DateTime> recovery_date { get; set; }
        public Nullable<decimal> recovery_amount { get; set; }
        public Nullable<int> recovery_amount_ccy_id { get; set; }
        public string recovery_means { get; set; }
        public string recovery_description { get; set; }
        public string recovery_circumstances { get; set; }
        public Nullable<decimal> recovery_cost { get; set; }
        public Nullable<int> recovery_cost_ccy_id { get; set; }
        public string adjustment_type { get; set; }
        public Nullable<decimal> adjustment_amount { get; set; }
        public Nullable<int> adjustment_amount_ccy_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> mitigant_id { get; set; }
        public Nullable<int> counterparty_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> mitigation_amount { get; set; }
        public Nullable<decimal> fees { get; set; }
        public Nullable<int> counterparty_id2 { get; set; }
        public Nullable<int> fees_currency_id { get; set; }
        public Nullable<int> recovery_action_fate_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> mitigation_amount_ccy { get; set; }
        public Nullable<System.DateTime> arrangement_date { get; set; }
        public string arrangement_description { get; set; }
        public Nullable<System.DateTime> arrangement_start_date { get; set; }
        public Nullable<System.DateTime> arrangement_end_date { get; set; }
        public Nullable<decimal> arrangement_amount { get; set; }
        public Nullable<int> arrangement_status_id { get; set; }
        public Nullable<int> arrangement_payment_number { get; set; }
        public Nullable<int> arrangement_amount_ccy { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual counterparty counterparty1 { get; set; }
        public virtual ICollection<counterparty_add_data_litigation> counterparty_add_data_litigation { get; set; }
        public virtual currency currency { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual currency currency2 { get; set; }
        public virtual currency currency3 { get; set; }
        public virtual currency currency4 { get; set; }
        public virtual mitigant mitigant { get; set; }
        public virtual recovery_action_fate recovery_action_fate { get; set; }
        public virtual ICollection<recovery_arrangement_action> recovery_arrangement_action { get; set; }
        public virtual ICollection<recovery_credit_event> recovery_credit_event { get; set; }
        public virtual recovery_type recovery_type { get; set; }
        public virtual software_user software_user { get; set; }
        public virtual status status { get; set; }
        public virtual status status1 { get; set; }
        public virtual ICollection<transaction_recovery_mitigant> transaction_recovery_mitigant { get; set; }
    }
}
