//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class transition_matrix
    {
        public int transition_matrix_id { get; set; }
        public System.DateTime transition_matrix_date { get; set; }
        public int rating_id_from { get; set; }
        public int rating_id_to { get; set; }
        public Nullable<decimal> transition_probability { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual rating rating { get; set; }
        public virtual rating rating1 { get; set; }
    }
}
