//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_credit_event
    {
        public transaction_credit_event()
        {
            this.payment_posting = new HashSet<payment_posting>();
            this.recovery_credit_event = new HashSet<recovery_credit_event>();
            this.transaction_credit_event_detail = new HashSet<transaction_credit_event_detail>();
        }
    
        public int credit_event_id { get; set; }
        public int transaction_id { get; set; }
        public string credit_event_shortname { get; set; }
        public Nullable<System.DateTime> credit_event_date { get; set; }
        public Nullable<System.DateTime> record_date { get; set; }
        public Nullable<int> credit_event_type_id { get; set; }
        public string credit_event_description { get; set; }
        public string credit_event_circumstances { get; set; }
        public Nullable<decimal> interest_amount { get; set; }
        public Nullable<int> interest_amount_currency_id { get; set; }
        public Nullable<decimal> unpaid_commission { get; set; }
        public Nullable<int> unpaid_currency_id { get; set; }
        public Nullable<decimal> fees { get; set; }
        public Nullable<int> fees_currency_id { get; set; }
        public Nullable<decimal> outstanding_amount { get; set; }
        public Nullable<int> outstanding_currency_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> amount_ccy_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual credit_event_type credit_event_type { get; set; }
        public virtual currency currency { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual currency currency2 { get; set; }
        public virtual currency currency3 { get; set; }
        public virtual ICollection<payment_posting> payment_posting { get; set; }
        public virtual ICollection<recovery_credit_event> recovery_credit_event { get; set; }
        public virtual status status { get; set; }
        public virtual transaction transaction { get; set; }
        public virtual ICollection<transaction_credit_event_detail> transaction_credit_event_detail { get; set; }
    }
}
