//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_reallocation
    {
        public int transaction_reallocation_id { get; set; }
        public Nullable<int> reallocation_type_id { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public Nullable<int> target_transaction_id { get; set; }
        public Nullable<decimal> reallocation_amount { get; set; }
        public Nullable<int> reallocation_amount_ccy_id { get; set; }
        public Nullable<int> target_internal_entity_id { get; set; }
        public Nullable<int> target_internal_segment_id { get; set; }
        public Nullable<int> target_counterparty_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string comment { get; set; }
        public string external_reference { get; set; }
        public Nullable<decimal> outstanding_amount { get; set; }
        public Nullable<int> outstanding_amount_ccy { get; set; }
        public Nullable<int> source_transaction_id { get; set; }
    
        public virtual counterparty counterparty { get; set; }
        public virtual currency currency { get; set; }
        public virtual currency currency1 { get; set; }
        public virtual internal_entity internal_entity { get; set; }
        public virtual internal_segment internal_segment { get; set; }
        public virtual status status { get; set; }
        public virtual transaction transaction { get; set; }
        public virtual transaction transaction1 { get; set; }
        public virtual transaction transaction2 { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
