//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAxeCreditFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_task_dispatch
    {
        public int wf_task_dispatch_id { get; set; }
        public int item_id { get; set; }
        public string item { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string dispatch_type { get; set; }
        public Nullable<System.DateTime> dispatch_start_date { get; set; }
        public Nullable<System.DateTime> dispatch_end_date { get; set; }
        public string dispatch_action { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> objective { get; set; }
        public Nullable<int> iuser { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> uuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> duser { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    
        public virtual group group { get; set; }
        public virtual software_user software_user { get; set; }
    }
}
